DROP   TABLE IF     EXISTS Colors;
CREATE TABLE IF NOT EXISTS Colors
( id				BIGINT				NOT NULL AUTO_INCREMENT
, updated_by		BIGINT				DEFAULT NULL
, updated_at		DATETIME			DEFAULT NULL
, status			VARCHAR(32)			DEFAULT 'Active'

, color_code		VARCHAR(32)			DEFAULT NULL
, color_type		VARCHAR(32)			DEFAULT NULL
, color_name		VARCHAR(255)		DEFAULT NULL
, dyeing_type		VARCHAR(32)			DEFAULT NULL
, remarks			TEXT				DEFAULT	NULL

, PRIMARY KEY	(id)
, UNIQUE		(color_code)
, KEY type		(color_type)
, KEY name		(color_name)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1
;

ALTER TABLE Colors			ADD COLUMN dyeing_type				VARCHAR(32)		DEFAULT NULL	AFTER color_name;

TRUNCATE TABLE	Colors;

INSERT INTO `Colors` (`id`, `updated_by`, `updated_at`, `status`, `color_code`, `color_type`, `color_name`, `dyeing_type`, `remarks`) VALUES
(100001, NULL, NULL, 'Active', NULL, 'CM', 'Abacaxi CMO', 'Tingir CMO', NULL),
(100002, NULL, NULL, 'Active', NULL, 'CM', 'Abacaxi CO', 'Tingir CO', NULL),
(100003, NULL, NULL, 'Active', NULL, 'CM', 'Abacaxi CV', 'Tingir CV', NULL),
(100004, NULL, NULL, 'Active', NULL, 'CM', 'Abacaxi Fio Tinto', 'Lavar', NULL),
(100005, NULL, NULL, 'Active', NULL, 'CM', 'Abacaxi PA', 'Tingir PA', NULL),
(100006, NULL, NULL, 'Active', NULL, 'CM', 'Abacaxi PES', 'Tingir PES', NULL),
(100007, NULL, NULL, 'Active', NULL, 'CM', 'Abacaxi PV', 'Tingir PV', NULL),
(100008, NULL, NULL, 'Active', NULL, 'CE', 'Alcachofra CMO', 'Tingir CMO', NULL),
(100009, NULL, NULL, 'Active', NULL, 'CE', 'Alcachofra CO', 'Tingir CO', NULL),
(100010, NULL, NULL, 'Active', NULL, 'CE', 'Alcachofra CV', 'Tingir CV', NULL),
(100011, NULL, NULL, 'Active', NULL, 'CE', 'Alcachofra Fio Tinto', 'Lavar', NULL),
(100012, NULL, NULL, 'Active', NULL, 'CE', 'Alcachofra PA', 'Tingir PA', NULL),
(100013, NULL, NULL, 'Active', NULL, 'CE', 'Alcachofra PES', 'Tingir PES', NULL),
(100014, NULL, NULL, 'Active', NULL, 'CE', 'Alcachofra PV', 'Tingir PV', NULL),
(100015, NULL, NULL, 'Active', NULL, 'Unico', 'Alvejado', 'Alvejar', NULL),
(100016, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo BR CMO', 'Tingir CMO', NULL),
(100017, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo BR CO', 'Tingir CO', NULL),
(100018, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo BR CV', 'Tingir CV', NULL),
(100019, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo BR Fio Tinto', 'Lavar', NULL),
(100020, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo BR PA', 'Tingir PA', NULL),
(100021, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo BR PES', 'Tingir PES', NULL),
(100022, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo BR PV', 'Tingir PV', NULL),
(100023, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo Citrico CMO', 'Tingir CMO', NULL),
(100024, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo Citrico CO', 'Tingir CO', NULL),
(100025, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo Citrico CV', 'Tingir CV', NULL),
(100026, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo Citrico Fio Tinto', 'Lavar', NULL),
(100027, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo Citrico PA', 'Tingir PA', NULL),
(100028, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo Citrico PES', 'Tingir PES', NULL),
(100029, NULL, NULL, 'Active', NULL, 'CM', 'Amarelo Citrico PV', 'Tingir PV', NULL),
(100030, NULL, NULL, 'Active', NULL, 'CI', 'Amarelo Fluor CMO', 'Tingir CMO', NULL),
(100031, NULL, NULL, 'Active', NULL, 'CI', 'Amarelo Fluor CO', 'Tingir CO', NULL),
(100032, NULL, NULL, 'Active', NULL, 'CI', 'Amarelo Fluor CV', 'Tingir CV', NULL),
(100033, NULL, NULL, 'Active', NULL, 'CI', 'Amarelo Fluor Fio Tinto', 'Lavar', NULL),
(100034, NULL, NULL, 'Active', NULL, 'CI', 'Amarelo Fluor PA', 'Tingir PA', NULL),
(100035, NULL, NULL, 'Active', NULL, 'CI', 'Amarelo Fluor PES', 'Tingir PES', NULL),
(100036, NULL, NULL, 'Active', NULL, 'CI', 'Amarelo Fluor PV', 'Tingir PV', NULL),
(100037, NULL, NULL, 'Active', NULL, 'CE', 'Amarelo Neon CMO', 'Tingir CMO', NULL),
(100038, NULL, NULL, 'Active', NULL, 'CE', 'Amarelo Neon CO', 'Tingir CO', NULL),
(100039, NULL, NULL, 'Active', NULL, 'CE', 'Amarelo Neon CV', 'Tingir CV', NULL),
(100040, NULL, NULL, 'Active', NULL, 'CE', 'Amarelo Neon Fio Tinto', 'Lavar', NULL),
(100041, NULL, NULL, 'Active', NULL, 'CE', 'Amarelo Neon PA', 'Tingir PA', NULL),
(100042, NULL, NULL, 'Active', NULL, 'CE', 'Amarelo Neon PES', 'Tingir PES', NULL),
(100043, NULL, NULL, 'Active', NULL, 'CE', 'Amarelo Neon PV', 'Tingir PV', NULL),
(100044, NULL, NULL, 'Active', NULL, 'CE', 'Amazon CMO', 'Tingir CMO', NULL),
(100045, NULL, NULL, 'Active', NULL, 'CE', 'Amazon CO', 'Tingir CO', NULL),
(100046, NULL, NULL, 'Active', NULL, 'CE', 'Amazon CV', 'Tingir CV', NULL),
(100047, NULL, NULL, 'Active', NULL, 'CE', 'Amazon Fio Tinto', 'Lavar', NULL),
(100048, NULL, NULL, 'Active', NULL, 'CE', 'Amazon PA', 'Tingir PA', NULL),
(100049, NULL, NULL, 'Active', NULL, 'CE', 'Amazon PES', 'Tingir PES', NULL),
(100050, NULL, NULL, 'Active', NULL, 'CE', 'Amazon PV', 'Tingir PV', NULL),
(100051, NULL, NULL, 'Active', NULL, 'CI', 'Amora CMO', 'Tingir CMO', NULL),
(100052, NULL, NULL, 'Active', NULL, 'CI', 'Amora CO', 'Tingir CO', NULL),
(100053, NULL, NULL, 'Active', NULL, 'CI', 'Amora CV', 'Tingir CV', NULL),
(100054, NULL, NULL, 'Active', NULL, 'CI', 'Amora Fio Tinto', 'Lavar', NULL),
(100055, NULL, NULL, 'Active', NULL, 'CI', 'Amora PA', 'Tingir PA', NULL),
(100056, NULL, NULL, 'Active', NULL, 'CI', 'Amora PES', 'Tingir PES', NULL),
(100057, NULL, NULL, 'Active', NULL, 'CI', 'Amora PV', 'Tingir PV', NULL),
(100058, NULL, NULL, 'Active', NULL, 'CC', 'Areia CMO', 'Tingir CMO', NULL),
(100059, NULL, NULL, 'Active', NULL, 'CC', 'Areia CO', 'Tingir CO', NULL),
(100060, NULL, NULL, 'Active', NULL, 'CC', 'Areia CV', 'Tingir CV', NULL),
(100061, NULL, NULL, 'Active', NULL, 'CC', 'Areia Fio Tinto', 'Lavar', NULL),
(100062, NULL, NULL, 'Active', NULL, 'CC', 'Areia PA', 'Tingir PA', NULL),
(100063, NULL, NULL, 'Active', NULL, 'CC', 'Areia PES', 'Tingir PES', NULL),
(100064, NULL, NULL, 'Active', NULL, 'CC', 'Areia PV', 'Tingir PV', NULL),
(100065, NULL, NULL, 'Active', NULL, 'CI', 'Azaleia CMO', 'Tingir CMO', NULL),
(100066, NULL, NULL, 'Active', NULL, 'CI', 'Azaleia CO', 'Tingir CO', NULL),
(100067, NULL, NULL, 'Active', NULL, 'CI', 'Azaleia CV', 'Tingir CV', NULL),
(100068, NULL, NULL, 'Active', NULL, 'CI', 'Azaleia Fio Tinto', 'Lavar', NULL),
(100069, NULL, NULL, 'Active', NULL, 'CI', 'Azaleia PA', 'Tingir PA', NULL),
(100070, NULL, NULL, 'Active', NULL, 'CI', 'Azaleia PES', 'Tingir PES', NULL),
(100071, NULL, NULL, 'Active', NULL, 'CI', 'Azaleia PV', 'Tingir PV', NULL),
(100072, NULL, NULL, 'Active', NULL, 'CE', 'Azul Bali CMO', 'Tingir CMO', NULL),
(100073, NULL, NULL, 'Active', NULL, 'CE', 'Azul Bali CO', 'Tingir CO', NULL),
(100074, NULL, NULL, 'Active', NULL, 'CE', 'Azul Bali CV', 'Tingir CV', NULL),
(100075, NULL, NULL, 'Active', NULL, 'CE', 'Azul Bali Fio Tinto', 'Lavar', NULL),
(100076, NULL, NULL, 'Active', NULL, 'CE', 'Azul Bali PA', 'Tingir PA', NULL),
(100077, NULL, NULL, 'Active', NULL, 'CE', 'Azul Bali PES', 'Tingir PES', NULL),
(100078, NULL, NULL, 'Active', NULL, 'CE', 'Azul Bali PV', 'Tingir PV', NULL),
(100079, NULL, NULL, 'Active', NULL, 'CE', 'Azul Cancun  CMO', 'Tingir CMO', NULL),
(100080, NULL, NULL, 'Active', NULL, 'CE', 'Azul Cancun  CO', 'Tingir CO', NULL),
(100081, NULL, NULL, 'Active', NULL, 'CE', 'Azul Cancun  CV', 'Tingir CV', NULL),
(100082, NULL, NULL, 'Active', NULL, 'CE', 'Azul Cancun  Fio Tinto', 'Lavar', NULL),
(100083, NULL, NULL, 'Active', NULL, 'CE', 'Azul Cancun  PA', 'Tingir PA', NULL),
(100084, NULL, NULL, 'Active', NULL, 'CE', 'Azul Cancun  PES', 'Tingir PES', NULL),
(100085, NULL, NULL, 'Active', NULL, 'CE', 'Azul Cancun  PV', 'Tingir PV', NULL),
(100086, NULL, NULL, 'Active', NULL, 'CI', 'Azul Genuino CMO', 'Tingir CMO', NULL),
(100087, NULL, NULL, 'Active', NULL, 'CI', 'Azul Genuino CO', 'Tingir CO', NULL),
(100088, NULL, NULL, 'Active', NULL, 'CI', 'Azul Genuino CV', 'Tingir CV', NULL),
(100089, NULL, NULL, 'Active', NULL, 'CI', 'Azul Genuino Fio Tinto', 'Lavar', NULL),
(100090, NULL, NULL, 'Active', NULL, 'CI', 'Azul Genuino PA', 'Tingir PA', NULL),
(100091, NULL, NULL, 'Active', NULL, 'CI', 'Azul Genuino PES', 'Tingir PES', NULL),
(100092, NULL, NULL, 'Active', NULL, 'CI', 'Azul Genuino PV', 'Tingir PV', NULL),
(100093, NULL, NULL, 'Active', NULL, 'CM', 'Azul Ilhabela CMO', 'Tingir CMO', NULL),
(100094, NULL, NULL, 'Active', NULL, 'CM', 'Azul Ilhabela CO', 'Tingir CO', NULL),
(100095, NULL, NULL, 'Active', NULL, 'CM', 'Azul Ilhabela CV', 'Tingir CV', NULL),
(100096, NULL, NULL, 'Active', NULL, 'CM', 'Azul Ilhabela Fio Tinto', 'Lavar', NULL),
(100097, NULL, NULL, 'Active', NULL, 'CM', 'Azul Ilhabela PA', 'Tingir PA', NULL),
(100098, NULL, NULL, 'Active', NULL, 'CM', 'Azul Ilhabela PES', 'Tingir PES', NULL),
(100099, NULL, NULL, 'Active', NULL, 'CM', 'Azul Ilhabela PV', 'Tingir PV', NULL),
(100100, NULL, NULL, 'Active', NULL, 'CE', 'Azul Mediterraneo CMO', 'Tingir CMO', NULL),
(100101, NULL, NULL, 'Active', NULL, 'CE', 'Azul Mediterraneo CO', 'Tingir CO', NULL),
(100102, NULL, NULL, 'Active', NULL, 'CE', 'Azul Mediterraneo CV', 'Tingir CV', NULL),
(100103, NULL, NULL, 'Active', NULL, 'CE', 'Azul Mediterraneo Fio Tinto', 'Lavar', NULL),
(100104, NULL, NULL, 'Active', NULL, 'CE', 'Azul Mediterraneo PA', 'Tingir PA', NULL),
(100105, NULL, NULL, 'Active', NULL, 'CE', 'Azul Mediterraneo PES', 'Tingir PES', NULL),
(100106, NULL, NULL, 'Active', NULL, 'CE', 'Azul Mediterraneo PV', 'Tingir PV', NULL),
(100107, NULL, NULL, 'Active', NULL, 'CI', 'Azul Ocean CMO', 'Tingir CMO', NULL),
(100108, NULL, NULL, 'Active', NULL, 'CI', 'Azul Ocean CO', 'Tingir CO', NULL),
(100109, NULL, NULL, 'Active', NULL, 'CI', 'Azul Ocean CV', 'Tingir CV', NULL),
(100110, NULL, NULL, 'Active', NULL, 'CI', 'Azul Ocean Fio Tinto', 'Lavar', NULL),
(100111, NULL, NULL, 'Active', NULL, 'CI', 'Azul Ocean PA', 'Tingir PA', NULL),
(100112, NULL, NULL, 'Active', NULL, 'CI', 'Azul Ocean PES', 'Tingir PES', NULL),
(100113, NULL, NULL, 'Active', NULL, 'CI', 'Azul Ocean PV', 'Tingir PV', NULL),
(100114, NULL, NULL, 'Active', NULL, 'CC', 'Azul Pacific CMO', 'Tingir CMO', NULL),
(100115, NULL, NULL, 'Active', NULL, 'CC', 'Azul Pacific CO', 'Tingir CO', NULL),
(100116, NULL, NULL, 'Active', NULL, 'CC', 'Azul Pacific CV', 'Tingir CV', NULL),
(100117, NULL, NULL, 'Active', NULL, 'CC', 'Azul Pacific Fio Tinto', 'Lavar', NULL),
(100118, NULL, NULL, 'Active', NULL, 'CC', 'Azul Pacific PA', 'Tingir PA', NULL),
(100119, NULL, NULL, 'Active', NULL, 'CC', 'Azul Pacific PES', 'Tingir PES', NULL),
(100120, NULL, NULL, 'Active', NULL, 'CC', 'Azul Pacific PV', 'Tingir PV', NULL),
(100121, NULL, NULL, 'Active', NULL, 'CI', 'Azul Patriota CMO', 'Tingir CMO', NULL),
(100122, NULL, NULL, 'Active', NULL, 'CI', 'Azul Patriota CO', 'Tingir CO', NULL),
(100123, NULL, NULL, 'Active', NULL, 'CI', 'Azul Patriota CV', 'Tingir CV', NULL),
(100124, NULL, NULL, 'Active', NULL, 'CI', 'Azul Patriota Fio Tinto', 'Lavar', NULL),
(100125, NULL, NULL, 'Active', NULL, 'CI', 'Azul Patriota PA', 'Tingir PA', NULL),
(100126, NULL, NULL, 'Active', NULL, 'CI', 'Azul Patriota PES', 'Tingir PES', NULL),
(100127, NULL, NULL, 'Active', NULL, 'CI', 'Azul Patriota PV', 'Tingir PV', NULL),
(100128, NULL, NULL, 'Active', NULL, 'CM', 'Azul Shake CMO', 'Tingir CMO', NULL),
(100129, NULL, NULL, 'Active', NULL, 'CM', 'Azul Shake CO', 'Tingir CO', NULL),
(100130, NULL, NULL, 'Active', NULL, 'CM', 'Azul Shake CV', 'Tingir CV', NULL),
(100131, NULL, NULL, 'Active', NULL, 'CM', 'Azul Shake Fio Tinto', 'Lavar', NULL),
(100132, NULL, NULL, 'Active', NULL, 'CM', 'Azul Shake PA', 'Tingir PA', NULL),
(100133, NULL, NULL, 'Active', NULL, 'CM', 'Azul Shake PES', 'Tingir PES', NULL),
(100134, NULL, NULL, 'Active', NULL, 'CM', 'Azul Shake PV', 'Tingir PV', NULL),
(100135, NULL, NULL, 'Active', NULL, 'CI', 'Azul Submarino CMO', 'Tingir CMO', NULL),
(100136, NULL, NULL, 'Active', NULL, 'CI', 'Azul Submarino CO', 'Tingir CO', NULL),
(100137, NULL, NULL, 'Active', NULL, 'CI', 'Azul Submarino CV', 'Tingir CV', NULL),
(100138, NULL, NULL, 'Active', NULL, 'CI', 'Azul Submarino Fio Tinto', 'Lavar', NULL),
(100139, NULL, NULL, 'Active', NULL, 'CI', 'Azul Submarino PA', 'Tingir PA', NULL),
(100140, NULL, NULL, 'Active', NULL, 'CI', 'Azul Submarino PES', 'Tingir PES', NULL),
(100141, NULL, NULL, 'Active', NULL, 'CI', 'Azul Submarino PV', 'Tingir PV', NULL),
(100142, NULL, NULL, 'Active', NULL, 'CE', 'Beringela CMO', 'Tingir CMO', NULL),
(100143, NULL, NULL, 'Active', NULL, 'CE', 'Beringela CO', 'Tingir CO', NULL),
(100144, NULL, NULL, 'Active', NULL, 'CE', 'Beringela CV', 'Tingir CV', NULL),
(100145, NULL, NULL, 'Active', NULL, 'CE', 'Beringela Fio Tinto', 'Lavar', NULL),
(100146, NULL, NULL, 'Active', NULL, 'CE', 'Beringela PA', 'Tingir PA', NULL),
(100147, NULL, NULL, 'Active', NULL, 'CE', 'Beringela PES', 'Tingir PES', NULL),
(100148, NULL, NULL, 'Active', NULL, 'CE', 'Beringela PV', 'Tingir PV', NULL),
(100149, NULL, NULL, 'Active', NULL, 'CM', 'Blue Monday CMO', 'Tingir CMO', NULL),
(100150, NULL, NULL, 'Active', NULL, 'CM', 'Blue Monday CO', 'Tingir CO', NULL),
(100151, NULL, NULL, 'Active', NULL, 'CM', 'Blue Monday CV', 'Tingir CV', NULL),
(100152, NULL, NULL, 'Active', NULL, 'CM', 'Blue Monday Fio Tinto', 'Lavar', NULL),
(100153, NULL, NULL, 'Active', NULL, 'CM', 'Blue Monday PA', 'Tingir PA', NULL),
(100154, NULL, NULL, 'Active', NULL, 'CM', 'Blue Monday PES', 'Tingir PES', NULL),
(100155, NULL, NULL, 'Active', NULL, 'CM', 'Blue Monday PV', 'Tingir PV', NULL),
(100156, NULL, NULL, 'Active', NULL, 'CM', 'Blush CMO', 'Tingir CMO', NULL),
(100157, NULL, NULL, 'Active', NULL, 'CM', 'Blush CO', 'Tingir CO', NULL),
(100158, NULL, NULL, 'Active', NULL, 'CM', 'Blush CV', 'Tingir CV', NULL),
(100159, NULL, NULL, 'Active', NULL, 'CM', 'Blush Fio Tinto', 'Lavar', NULL),
(100160, NULL, NULL, 'Active', NULL, 'CM', 'Blush PA', 'Tingir PA', NULL),
(100161, NULL, NULL, 'Active', NULL, 'CM', 'Blush PES', 'Tingir PES', NULL),
(100162, NULL, NULL, 'Active', NULL, 'CM', 'Blush PV', 'Tingir PV', NULL),
(100163, NULL, NULL, 'Active', NULL, 'CE', 'Bordo CMO', 'Tingir CMO', NULL),
(100164, NULL, NULL, 'Active', NULL, 'CE', 'Bordo CO', 'Tingir CO', NULL),
(100165, NULL, NULL, 'Active', NULL, 'CE', 'Bordo CV', 'Tingir CV', NULL),
(100166, NULL, NULL, 'Active', NULL, 'CE', 'Bordo Fio Tinto', 'Lavar', NULL),
(100167, NULL, NULL, 'Active', NULL, 'CE', 'Bordo PA', 'Tingir PA', NULL),
(100168, NULL, NULL, 'Active', NULL, 'CE', 'Bordo PES', 'Tingir PES', NULL),
(100169, NULL, NULL, 'Active', NULL, 'CE', 'Bordo PV', 'Tingir PV', NULL),
(100170, NULL, NULL, 'Active', NULL, 'CB', 'Branco CMO', 'Tingir CMO', NULL),
(100171, NULL, NULL, 'Active', NULL, 'CB', 'Branco CO', 'Tingir CO', NULL),
(100172, NULL, NULL, 'Active', NULL, 'CB', 'Branco CV', 'Tingir CV', NULL),
(100173, NULL, NULL, 'Active', NULL, 'CB', 'Branco Fio Tinto', 'Lavar', NULL),
(100174, NULL, NULL, 'Active', NULL, 'CB', 'Branco PA', 'Tingir PA', NULL),
(100175, NULL, NULL, 'Active', NULL, 'CB', 'Branco PES', 'Tingir PES', NULL),
(100176, NULL, NULL, 'Active', NULL, 'CB', 'Branco PV', 'Tingir PV', NULL),
(100177, NULL, NULL, 'Active', NULL, 'CC', 'Camafel CMO', 'Tingir CMO', NULL),
(100178, NULL, NULL, 'Active', NULL, 'CC', 'Camafel CO', 'Tingir CO', NULL),
(100179, NULL, NULL, 'Active', NULL, 'CC', 'Camafel CV', 'Tingir CV', NULL),
(100180, NULL, NULL, 'Active', NULL, 'CC', 'Camafel Fio Tinto', 'Lavar', NULL),
(100181, NULL, NULL, 'Active', NULL, 'CC', 'Camafel PA', 'Tingir PA', NULL),
(100182, NULL, NULL, 'Active', NULL, 'CC', 'Camafel PES', 'Tingir PES', NULL),
(100183, NULL, NULL, 'Active', NULL, 'CC', 'Camafel PV', 'Tingir PV', NULL),
(100184, NULL, NULL, 'Active', NULL, 'CI', 'Camurca CMO', 'Tingir CMO', NULL),
(100185, NULL, NULL, 'Active', NULL, 'CI', 'Camurca CO', 'Tingir CO', NULL),
(100186, NULL, NULL, 'Active', NULL, 'CI', 'Camurca CV', 'Tingir CV', NULL),
(100187, NULL, NULL, 'Active', NULL, 'CI', 'Camurca Fio Tinto', 'Lavar', NULL),
(100188, NULL, NULL, 'Active', NULL, 'CI', 'Camurca PA', 'Tingir PA', NULL),
(100189, NULL, NULL, 'Active', NULL, 'CI', 'Camurca PES', 'Tingir PES', NULL),
(100190, NULL, NULL, 'Active', NULL, 'CI', 'Camurca PV', 'Tingir PV', NULL),
(100191, NULL, NULL, 'Active', NULL, 'CC', 'Canario CMO', 'Tingir CMO', NULL),
(100192, NULL, NULL, 'Active', NULL, 'CC', 'Canario CO', 'Tingir CO', NULL),
(100193, NULL, NULL, 'Active', NULL, 'CC', 'Canario CV', 'Tingir CV', NULL),
(100194, NULL, NULL, 'Active', NULL, 'CC', 'Canario Fio Tinto', 'Lavar', NULL),
(100195, NULL, NULL, 'Active', NULL, 'CC', 'Canario PA', 'Tingir PA', NULL),
(100196, NULL, NULL, 'Active', NULL, 'CC', 'Canario PES', 'Tingir PES', NULL),
(100197, NULL, NULL, 'Active', NULL, 'CC', 'Canario PV', 'Tingir PV', NULL),
(100198, NULL, NULL, 'Active', NULL, 'CE', 'Carbono CMO', 'Tingir CMO', NULL),
(100199, NULL, NULL, 'Active', NULL, 'CE', 'Carbono CO', 'Tingir CO', NULL),
(100200, NULL, NULL, 'Active', NULL, 'CE', 'Carbono CV', 'Tingir CV', NULL),
(100201, NULL, NULL, 'Active', NULL, 'CE', 'Carbono Fio Tinto', 'Lavar', NULL),
(100202, NULL, NULL, 'Active', NULL, 'CE', 'Carbono PA', 'Tingir PA', NULL),
(100203, NULL, NULL, 'Active', NULL, 'CE', 'Carbono PES', 'Tingir PES', NULL),
(100204, NULL, NULL, 'Active', NULL, 'CE', 'Carbono PV', 'Tingir PV', NULL),
(100205, NULL, NULL, 'Active', NULL, 'CI', 'Cerejinha CMO', 'Tingir CMO', NULL),
(100206, NULL, NULL, 'Active', NULL, 'CI', 'Cerejinha CO', 'Tingir CO', NULL),
(100207, NULL, NULL, 'Active', NULL, 'CI', 'Cerejinha CV', 'Tingir CV', NULL),
(100208, NULL, NULL, 'Active', NULL, 'CI', 'Cerejinha Fio Tinto', 'Lavar', NULL),
(100209, NULL, NULL, 'Active', NULL, 'CI', 'Cerejinha PA', 'Tingir PA', NULL),
(100210, NULL, NULL, 'Active', NULL, 'CI', 'Cerejinha PES', 'Tingir PES', NULL),
(100211, NULL, NULL, 'Active', NULL, 'CI', 'Cerejinha PV', 'Tingir PV', NULL),
(100212, NULL, NULL, 'Active', NULL, 'CE', 'Chocolate CMO', 'Tingir CMO', NULL),
(100213, NULL, NULL, 'Active', NULL, 'CE', 'Chocolate CO', 'Tingir CO', NULL),
(100214, NULL, NULL, 'Active', NULL, 'CE', 'Chocolate CV', 'Tingir CV', NULL),
(100215, NULL, NULL, 'Active', NULL, 'CE', 'Chocolate Fio Tinto', 'Lavar', NULL),
(100216, NULL, NULL, 'Active', NULL, 'CE', 'Chocolate PA', 'Tingir PA', NULL),
(100217, NULL, NULL, 'Active', NULL, 'CE', 'Chocolate PES', 'Tingir PES', NULL),
(100218, NULL, NULL, 'Active', NULL, 'CE', 'Chocolate PV', 'Tingir PV', NULL),
(100219, NULL, NULL, 'Active', NULL, 'CI', 'Chumbo Sarah CMO', 'Tingir CMO', NULL),
(100220, NULL, NULL, 'Active', NULL, 'CI', 'Chumbo Sarah CO', 'Tingir CO', NULL),
(100221, NULL, NULL, 'Active', NULL, 'CI', 'Chumbo Sarah CV', 'Tingir CV', NULL),
(100222, NULL, NULL, 'Active', NULL, 'CI', 'Chumbo Sarah Fio Tinto', 'Lavar', NULL),
(100223, NULL, NULL, 'Active', NULL, 'CI', 'Chumbo Sarah PA', 'Tingir PA', NULL),
(100224, NULL, NULL, 'Active', NULL, 'CI', 'Chumbo Sarah PES', 'Tingir PES', NULL),
(100225, NULL, NULL, 'Active', NULL, 'CI', 'Chumbo Sarah PV', 'Tingir PV', NULL),
(100226, NULL, NULL, 'Active', NULL, 'CE', 'Clorofila CMO', 'Tingir CMO', NULL),
(100227, NULL, NULL, 'Active', NULL, 'CE', 'Clorofila CO', 'Tingir CO', NULL),
(100228, NULL, NULL, 'Active', NULL, 'CE', 'Clorofila CV', 'Tingir CV', NULL),
(100229, NULL, NULL, 'Active', NULL, 'CE', 'Clorofila Fio Tinto', 'Lavar', NULL),
(100230, NULL, NULL, 'Active', NULL, 'CE', 'Clorofila PA', 'Tingir PA', NULL),
(100231, NULL, NULL, 'Active', NULL, 'CE', 'Clorofila PES', 'Tingir PES', NULL),
(100232, NULL, NULL, 'Active', NULL, 'CE', 'Clorofila PV', 'Tingir PV', NULL),
(100233, NULL, NULL, 'Active', NULL, 'CI', 'Coral Fluor CMO', 'Tingir CMO', NULL),
(100234, NULL, NULL, 'Active', NULL, 'CI', 'Coral Fluor CO', 'Tingir CO', NULL),
(100235, NULL, NULL, 'Active', NULL, 'CI', 'Coral Fluor CV', 'Tingir CV', NULL),
(100236, NULL, NULL, 'Active', NULL, 'CI', 'Coral Fluor Fio Tinto', 'Lavar', NULL),
(100237, NULL, NULL, 'Active', NULL, 'CI', 'Coral Fluor PA', 'Tingir PA', NULL),
(100238, NULL, NULL, 'Active', NULL, 'CI', 'Coral Fluor PES', 'Tingir PES', NULL),
(100239, NULL, NULL, 'Active', NULL, 'CI', 'Coral Fluor PV', 'Tingir PV', NULL),
(100240, NULL, NULL, 'Active', NULL, 'CB', 'Cru', '', NULL),
(100241, NULL, NULL, 'Active', NULL, 'CB', 'Cru de Maquina', '', NULL),
(100242, NULL, NULL, 'Active', NULL, 'CI', 'Crush CMO', 'Tingir CMO', NULL),
(100243, NULL, NULL, 'Active', NULL, 'CI', 'Crush CO', 'Tingir CO', NULL),
(100244, NULL, NULL, 'Active', NULL, 'CI', 'Crush CV', 'Tingir CV', NULL),
(100245, NULL, NULL, 'Active', NULL, 'CI', 'Crush Fio Tinto', 'Lavar', NULL),
(100246, NULL, NULL, 'Active', NULL, 'CI', 'Crush PA', 'Tingir PA', NULL),
(100247, NULL, NULL, 'Active', NULL, 'CI', 'Crush PES', 'Tingir PES', NULL),
(100248, NULL, NULL, 'Active', NULL, 'CI', 'Crush PV', 'Tingir PV', NULL),
(100249, NULL, NULL, 'Active', NULL, 'CM', 'Curry CMO', 'Tingir CMO', NULL),
(100250, NULL, NULL, 'Active', NULL, 'CM', 'Curry CO', 'Tingir CO', NULL),
(100251, NULL, NULL, 'Active', NULL, 'CM', 'Curry CV', 'Tingir CV', NULL),
(100252, NULL, NULL, 'Active', NULL, 'CM', 'Curry Fio Tinto', 'Lavar', NULL),
(100253, NULL, NULL, 'Active', NULL, 'CM', 'Curry PA', 'Tingir PA', NULL),
(100254, NULL, NULL, 'Active', NULL, 'CM', 'Curry PES', 'Tingir PES', NULL),
(100255, NULL, NULL, 'Active', NULL, 'CM', 'Curry PV', 'Tingir PV', NULL),
(100256, NULL, NULL, 'Active', NULL, 'CM', 'Dalia CMO', 'Tingir CMO', NULL),
(100257, NULL, NULL, 'Active', NULL, 'CM', 'Dalia CO', 'Tingir CO', NULL),
(100258, NULL, NULL, 'Active', NULL, 'CM', 'Dalia CV', 'Tingir CV', NULL),
(100259, NULL, NULL, 'Active', NULL, 'CM', 'Dalia Fio Tinto', 'Lavar', NULL),
(100260, NULL, NULL, 'Active', NULL, 'CM', 'Dalia PA', 'Tingir PA', NULL),
(100261, NULL, NULL, 'Active', NULL, 'CM', 'Dalia PES', 'Tingir PES', NULL),
(100262, NULL, NULL, 'Active', NULL, 'CM', 'Dalia PV', 'Tingir PV', NULL),
(100263, NULL, NULL, 'Active', NULL, 'CC', 'Damasco CMO', 'Tingir CMO', NULL),
(100264, NULL, NULL, 'Active', NULL, 'CC', 'Damasco CO', 'Tingir CO', NULL),
(100265, NULL, NULL, 'Active', NULL, 'CC', 'Damasco CV', 'Tingir CV', NULL),
(100266, NULL, NULL, 'Active', NULL, 'CC', 'Damasco Fio Tinto', 'Lavar', NULL),
(100267, NULL, NULL, 'Active', NULL, 'CC', 'Damasco PA', 'Tingir PA', NULL),
(100268, NULL, NULL, 'Active', NULL, 'CC', 'Damasco PES', 'Tingir PES', NULL),
(100269, NULL, NULL, 'Active', NULL, 'CC', 'Damasco PV', 'Tingir PV', NULL),
(100270, NULL, NULL, 'Active', NULL, 'CI', 'Esmeralda CMO', 'Tingir CMO', NULL),
(100271, NULL, NULL, 'Active', NULL, 'CI', 'Esmeralda CO', 'Tingir CO', NULL),
(100272, NULL, NULL, 'Active', NULL, 'CI', 'Esmeralda CV', 'Tingir CV', NULL),
(100273, NULL, NULL, 'Active', NULL, 'CI', 'Esmeralda Fio Tinto', 'Lavar', NULL),
(100274, NULL, NULL, 'Active', NULL, 'CI', 'Esmeralda PA', 'Tingir PA', NULL),
(100275, NULL, NULL, 'Active', NULL, 'CI', 'Esmeralda PES', 'Tingir PES', NULL),
(100276, NULL, NULL, 'Active', NULL, 'CI', 'Esmeralda PV', 'Tingir PV', NULL),
(100277, NULL, NULL, 'Active', NULL, 'CE', 'Framboesa CMO', 'Tingir CMO', NULL),
(100278, NULL, NULL, 'Active', NULL, 'CE', 'Framboesa CO', 'Tingir CO', NULL),
(100279, NULL, NULL, 'Active', NULL, 'CE', 'Framboesa CV', 'Tingir CV', NULL),
(100280, NULL, NULL, 'Active', NULL, 'CE', 'Framboesa Fio Tinto', 'Lavar', NULL),
(100281, NULL, NULL, 'Active', NULL, 'CE', 'Framboesa PA', 'Tingir PA', NULL),
(100282, NULL, NULL, 'Active', NULL, 'CE', 'Framboesa PES', 'Tingir PES', NULL),
(100283, NULL, NULL, 'Active', NULL, 'CE', 'Framboesa PV', 'Tingir PV', NULL),
(100284, NULL, NULL, 'Active', NULL, 'CE', 'Galapagos Star I CMO', 'Tingir CMO', NULL),
(100285, NULL, NULL, 'Active', NULL, 'CE', 'Galapagos Star I CO', 'Tingir CO', NULL),
(100286, NULL, NULL, 'Active', NULL, 'CE', 'Galapagos Star I CV', 'Tingir CV', NULL),
(100287, NULL, NULL, 'Active', NULL, 'CE', 'Galapagos Star I Fio Tinto', 'Lavar', NULL),
(100288, NULL, NULL, 'Active', NULL, 'CE', 'Galapagos Star I PA', 'Tingir PA', NULL),
(100289, NULL, NULL, 'Active', NULL, 'CE', 'Galapagos Star I PES', 'Tingir PES', NULL),
(100290, NULL, NULL, 'Active', NULL, 'CE', 'Galapagos Star I PV', 'Tingir PV', NULL),
(100291, NULL, NULL, 'Active', NULL, 'CC', 'Ganache CMO', 'Tingir CMO', NULL),
(100292, NULL, NULL, 'Active', NULL, 'CC', 'Ganache CO', 'Tingir CO', NULL),
(100293, NULL, NULL, 'Active', NULL, 'CC', 'Ganache CV', 'Tingir CV', NULL),
(100294, NULL, NULL, 'Active', NULL, 'CC', 'Ganache Fio Tinto', 'Lavar', NULL),
(100295, NULL, NULL, 'Active', NULL, 'CC', 'Ganache PA', 'Tingir PA', NULL),
(100296, NULL, NULL, 'Active', NULL, 'CC', 'Ganache PES', 'Tingir PES', NULL),
(100297, NULL, NULL, 'Active', NULL, 'CC', 'Ganache PV', 'Tingir PV', NULL),
(100298, NULL, NULL, 'Active', NULL, 'CM', 'Gelado CMO', 'Tingir CMO', NULL),
(100299, NULL, NULL, 'Active', NULL, 'CM', 'Gelado CO', 'Tingir CO', NULL),
(100300, NULL, NULL, 'Active', NULL, 'CM', 'Gelado CV', 'Tingir CV', NULL),
(100301, NULL, NULL, 'Active', NULL, 'CM', 'Gelado Fio Tinto', 'Lavar', NULL),
(100302, NULL, NULL, 'Active', NULL, 'CM', 'Gelado PA', 'Tingir PA', NULL),
(100303, NULL, NULL, 'Active', NULL, 'CM', 'Gelado PES', 'Tingir PES', NULL),
(100304, NULL, NULL, 'Active', NULL, 'CM', 'Gelado PV', 'Tingir PV', NULL),
(100305, NULL, NULL, 'Active', NULL, 'CC', 'Gelo CMO', 'Tingir CMO', NULL),
(100306, NULL, NULL, 'Active', NULL, 'CC', 'Gelo CO', 'Tingir CO', NULL),
(100307, NULL, NULL, 'Active', NULL, 'CC', 'Gelo CV', 'Tingir CV', NULL),
(100308, NULL, NULL, 'Active', NULL, 'CC', 'Gelo Fio Tinto', 'Lavar', NULL),
(100309, NULL, NULL, 'Active', NULL, 'CC', 'Gelo PA', 'Tingir PA', NULL),
(100310, NULL, NULL, 'Active', NULL, 'CC', 'Gelo PES', 'Tingir PES', NULL),
(100311, NULL, NULL, 'Active', NULL, 'CC', 'Gelo PV', 'Tingir PV', NULL),
(100312, NULL, NULL, 'Active', NULL, 'CM', 'Girassol CMO', 'Tingir CMO', NULL),
(100313, NULL, NULL, 'Active', NULL, 'CM', 'Girassol CO', 'Tingir CO', NULL),
(100314, NULL, NULL, 'Active', NULL, 'CM', 'Girassol CV', 'Tingir CV', NULL),
(100315, NULL, NULL, 'Active', NULL, 'CM', 'Girassol Fio Tinto', 'Lavar', NULL),
(100316, NULL, NULL, 'Active', NULL, 'CM', 'Girassol PA', 'Tingir PA', NULL),
(100317, NULL, NULL, 'Active', NULL, 'CM', 'Girassol PES', 'Tingir PES', NULL),
(100318, NULL, NULL, 'Active', NULL, 'CM', 'Girassol PV', 'Tingir PV', NULL),
(100319, NULL, NULL, 'Active', NULL, 'CM', 'Goiaba CMO', 'Tingir CMO', NULL),
(100320, NULL, NULL, 'Active', NULL, 'CM', 'Goiaba CO', 'Tingir CO', NULL),
(100321, NULL, NULL, 'Active', NULL, 'CM', 'Goiaba CV', 'Tingir CV', NULL),
(100322, NULL, NULL, 'Active', NULL, 'CM', 'Goiaba Fio Tinto', 'Lavar', NULL),
(100323, NULL, NULL, 'Active', NULL, 'CM', 'Goiaba PA', 'Tingir PA', NULL),
(100324, NULL, NULL, 'Active', NULL, 'CM', 'Goiaba PES', 'Tingir PES', NULL),
(100325, NULL, NULL, 'Active', NULL, 'CM', 'Goiaba PV', 'Tingir PV', NULL),
(100326, NULL, NULL, 'Active', NULL, 'CE', 'Grapette CMO', 'Tingir CMO', NULL),
(100327, NULL, NULL, 'Active', NULL, 'CE', 'Grapette CO', 'Tingir CO', NULL),
(100328, NULL, NULL, 'Active', NULL, 'CE', 'Grapette CV', 'Tingir CV', NULL),
(100329, NULL, NULL, 'Active', NULL, 'CE', 'Grapette Fio Tinto', 'Lavar', NULL),
(100330, NULL, NULL, 'Active', NULL, 'CE', 'Grapette PA', 'Tingir PA', NULL),
(100331, NULL, NULL, 'Active', NULL, 'CE', 'Grapette PES', 'Tingir PES', NULL),
(100332, NULL, NULL, 'Active', NULL, 'CE', 'Grapette PV', 'Tingir PV', NULL),
(100333, NULL, NULL, 'Active', NULL, 'CI', 'Hibisco CMO', 'Tingir CMO', NULL),
(100334, NULL, NULL, 'Active', NULL, 'CI', 'Hibisco CO', 'Tingir CO', NULL),
(100335, NULL, NULL, 'Active', NULL, 'CI', 'Hibisco CV', 'Tingir CV', NULL),
(100336, NULL, NULL, 'Active', NULL, 'CI', 'Hibisco Fio Tinto', 'Lavar', NULL),
(100337, NULL, NULL, 'Active', NULL, 'CI', 'Hibisco PA', 'Tingir PA', NULL),
(100338, NULL, NULL, 'Active', NULL, 'CI', 'Hibisco PES', 'Tingir PES', NULL),
(100339, NULL, NULL, 'Active', NULL, 'CI', 'Hibisco PV', 'Tingir PV', NULL),
(100340, NULL, NULL, 'Active', NULL, 'CM', 'Indigo CMO', 'Tingir CMO', NULL),
(100341, NULL, NULL, 'Active', NULL, 'CM', 'Indigo CO', 'Tingir CO', NULL),
(100342, NULL, NULL, 'Active', NULL, 'CM', 'Indigo CV', 'Tingir CV', NULL),
(100343, NULL, NULL, 'Active', NULL, 'CM', 'Indigo Fio Tinto', 'Lavar', NULL),
(100344, NULL, NULL, 'Active', NULL, 'CM', 'Indigo PA', 'Tingir PA', NULL),
(100345, NULL, NULL, 'Active', NULL, 'CM', 'Indigo PES', 'Tingir PES', NULL),
(100346, NULL, NULL, 'Active', NULL, 'CM', 'Indigo PV', 'Tingir PV', NULL),
(100347, NULL, NULL, 'Active', NULL, 'CM', 'Inhame CMO', 'Tingir CMO', NULL),
(100348, NULL, NULL, 'Active', NULL, 'CM', 'Inhame CO', 'Tingir CO', NULL),
(100349, NULL, NULL, 'Active', NULL, 'CM', 'Inhame CV', 'Tingir CV', NULL),
(100350, NULL, NULL, 'Active', NULL, 'CM', 'Inhame Fio Tinto', 'Lavar', NULL),
(100351, NULL, NULL, 'Active', NULL, 'CM', 'Inhame PA', 'Tingir PA', NULL),
(100352, NULL, NULL, 'Active', NULL, 'CM', 'Inhame PES', 'Tingir PES', NULL),
(100353, NULL, NULL, 'Active', NULL, 'CM', 'Inhame PV', 'Tingir PV', NULL),
(100354, NULL, NULL, 'Active', NULL, 'CC', 'Jasmim CMO', 'Tingir CMO', NULL),
(100355, NULL, NULL, 'Active', NULL, 'CC', 'Jasmim CO', 'Tingir CO', NULL),
(100356, NULL, NULL, 'Active', NULL, 'CC', 'Jasmim CV', 'Tingir CV', NULL),
(100357, NULL, NULL, 'Active', NULL, 'CC', 'Jasmim Fio Tinto', 'Lavar', NULL),
(100358, NULL, NULL, 'Active', NULL, 'CC', 'Jasmim PA', 'Tingir PA', NULL),
(100359, NULL, NULL, 'Active', NULL, 'CC', 'Jasmim PES', 'Tingir PES', NULL),
(100360, NULL, NULL, 'Active', NULL, 'CC', 'Jasmim PV', 'Tingir PV', NULL),
(100361, NULL, NULL, 'Active', NULL, 'CM', 'Laranja Queimado CMO', 'Tingir CMO', NULL),
(100362, NULL, NULL, 'Active', NULL, 'CM', 'Laranja Queimado CO', 'Tingir CO', NULL),
(100363, NULL, NULL, 'Active', NULL, 'CM', 'Laranja Queimado CV', 'Tingir CV', NULL),
(100364, NULL, NULL, 'Active', NULL, 'CM', 'Laranja Queimado Fio Tinto', 'Lavar', NULL),
(100365, NULL, NULL, 'Active', NULL, 'CM', 'Laranja Queimado PA', 'Tingir PA', NULL),
(100366, NULL, NULL, 'Active', NULL, 'CM', 'Laranja Queimado PES', 'Tingir PES', NULL),
(100367, NULL, NULL, 'Active', NULL, 'CM', 'Laranja Queimado PV', 'Tingir PV', NULL),
(100368, NULL, NULL, 'Active', NULL, 'CI', 'Laranjina CMO', 'Tingir CMO', NULL),
(100369, NULL, NULL, 'Active', NULL, 'CI', 'Laranjina CO', 'Tingir CO', NULL),
(100370, NULL, NULL, 'Active', NULL, 'CI', 'Laranjina CV', 'Tingir CV', NULL),
(100371, NULL, NULL, 'Active', NULL, 'CI', 'Laranjina Fio Tinto', 'Lavar', NULL),
(100372, NULL, NULL, 'Active', NULL, 'CI', 'Laranjina PA', 'Tingir PA', NULL),
(100373, NULL, NULL, 'Active', NULL, 'CI', 'Laranjina PES', 'Tingir PES', NULL),
(100374, NULL, NULL, 'Active', NULL, 'CI', 'Laranjina PV', 'Tingir PV', NULL),
(100375, NULL, NULL, 'Active', NULL, 'Unico', 'Lavado', 'Lavar', NULL),
(100376, NULL, NULL, 'Active', NULL, 'CC', 'Lavanda CMO', 'Tingir CMO', NULL),
(100377, NULL, NULL, 'Active', NULL, 'CC', 'Lavanda CO', 'Tingir CO', NULL),
(100378, NULL, NULL, 'Active', NULL, 'CC', 'Lavanda CV', 'Tingir CV', NULL),
(100379, NULL, NULL, 'Active', NULL, 'CC', 'Lavanda Fio Tinto', 'Lavar', NULL),
(100380, NULL, NULL, 'Active', NULL, 'CC', 'Lavanda PA', 'Tingir PA', NULL),
(100381, NULL, NULL, 'Active', NULL, 'CC', 'Lavanda PES', 'Tingir PES', NULL),
(100382, NULL, NULL, 'Active', NULL, 'CC', 'Lavanda PV', 'Tingir PV', NULL),
(100383, NULL, NULL, 'Active', NULL, 'CI', 'Lemon CMO', 'Tingir CMO', NULL),
(100384, NULL, NULL, 'Active', NULL, 'CI', 'Lemon CO', 'Tingir CO', NULL),
(100385, NULL, NULL, 'Active', NULL, 'CI', 'Lemon CV', 'Tingir CV', NULL),
(100386, NULL, NULL, 'Active', NULL, 'CI', 'Lemon Fio Tinto', 'Lavar', NULL),
(100387, NULL, NULL, 'Active', NULL, 'CI', 'Lemon PA', 'Tingir PA', NULL),
(100388, NULL, NULL, 'Active', NULL, 'CI', 'Lemon PES', 'Tingir PES', NULL),
(100389, NULL, NULL, 'Active', NULL, 'CI', 'Lemon PV', 'Tingir PV', NULL),
(100390, NULL, NULL, 'Active', NULL, 'CM', 'Lilac CMO', 'Tingir CMO', NULL),
(100391, NULL, NULL, 'Active', NULL, 'CM', 'Lilac CO', 'Tingir CO', NULL),
(100392, NULL, NULL, 'Active', NULL, 'CM', 'Lilac CV', 'Tingir CV', NULL),
(100393, NULL, NULL, 'Active', NULL, 'CM', 'Lilac Fio Tinto', 'Lavar', NULL),
(100394, NULL, NULL, 'Active', NULL, 'CM', 'Lilac PA', 'Tingir PA', NULL),
(100395, NULL, NULL, 'Active', NULL, 'CM', 'Lilac PES', 'Tingir PES', NULL),
(100396, NULL, NULL, 'Active', NULL, 'CM', 'Lilac PV', 'Tingir PV', NULL),
(100397, NULL, NULL, 'Active', NULL, 'CM', 'Lilas CMO', 'Tingir CMO', NULL),
(100398, NULL, NULL, 'Active', NULL, 'CM', 'Lilas CO', 'Tingir CO', NULL),
(100399, NULL, NULL, 'Active', NULL, 'CM', 'Lilas CV', 'Tingir CV', NULL),
(100400, NULL, NULL, 'Active', NULL, 'CM', 'Lilas Fio Tinto', 'Lavar', NULL),
(100401, NULL, NULL, 'Active', NULL, 'CM', 'Lilas PA', 'Tingir PA', NULL),
(100402, NULL, NULL, 'Active', NULL, 'CM', 'Lilas PES', 'Tingir PES', NULL),
(100403, NULL, NULL, 'Active', NULL, 'CM', 'Lilas PV', 'Tingir PV', NULL),
(100404, NULL, NULL, 'Active', NULL, 'CI', 'Lima CMO', 'Tingir CMO', NULL),
(100405, NULL, NULL, 'Active', NULL, 'CI', 'Lima CO', 'Tingir CO', NULL),
(100406, NULL, NULL, 'Active', NULL, 'CI', 'Lima CV', 'Tingir CV', NULL),
(100407, NULL, NULL, 'Active', NULL, 'CI', 'Lima Fio Tinto', 'Lavar', NULL),
(100408, NULL, NULL, 'Active', NULL, 'CI', 'Lima PA', 'Tingir PA', NULL),
(100409, NULL, NULL, 'Active', NULL, 'CI', 'Lima PES', 'Tingir PES', NULL),
(100410, NULL, NULL, 'Active', NULL, 'CI', 'Lima PV', 'Tingir PV', NULL),
(100411, NULL, NULL, 'Active', NULL, 'CC', 'Limone CMO', 'Tingir CMO', NULL),
(100412, NULL, NULL, 'Active', NULL, 'CC', 'Limone CO', 'Tingir CO', NULL),
(100413, NULL, NULL, 'Active', NULL, 'CC', 'Limone CV', 'Tingir CV', NULL),
(100414, NULL, NULL, 'Active', NULL, 'CC', 'Limone Fio Tinto', 'Lavar', NULL),
(100415, NULL, NULL, 'Active', NULL, 'CC', 'Limone PA', 'Tingir PA', NULL),
(100416, NULL, NULL, 'Active', NULL, 'CC', 'Limone PES', 'Tingir PES', NULL),
(100417, NULL, NULL, 'Active', NULL, 'CC', 'Limone PV', 'Tingir PV', NULL),
(100418, NULL, NULL, 'Active', NULL, 'CM', 'Lips CMO', 'Tingir CMO', NULL),
(100419, NULL, NULL, 'Active', NULL, 'CM', 'Lips CO', 'Tingir CO', NULL),
(100420, NULL, NULL, 'Active', NULL, 'CM', 'Lips CV', 'Tingir CV', NULL),
(100421, NULL, NULL, 'Active', NULL, 'CM', 'Lips Fio Tinto', 'Lavar', NULL),
(100422, NULL, NULL, 'Active', NULL, 'CM', 'Lips PA', 'Tingir PA', NULL),
(100423, NULL, NULL, 'Active', NULL, 'CM', 'Lips PES', 'Tingir PES', NULL),
(100424, NULL, NULL, 'Active', NULL, 'CM', 'Lips PV', 'Tingir PV', NULL),
(100425, NULL, NULL, 'Active', NULL, 'CM', 'Mare CMO', 'Tingir CMO', NULL),
(100426, NULL, NULL, 'Active', NULL, 'CM', 'Mare CO', 'Tingir CO', NULL),
(100427, NULL, NULL, 'Active', NULL, 'CM', 'Mare CV', 'Tingir CV', NULL),
(100428, NULL, NULL, 'Active', NULL, 'CM', 'Mare Fio Tinto', 'Lavar', NULL),
(100429, NULL, NULL, 'Active', NULL, 'CM', 'Mare PA', 'Tingir PA', NULL),
(100430, NULL, NULL, 'Active', NULL, 'CM', 'Mare PES', 'Tingir PES', NULL),
(100431, NULL, NULL, 'Active', NULL, 'CM', 'Mare PV', 'Tingir PV', NULL),
(100432, NULL, NULL, 'Active', NULL, 'CC', 'Marfim CMO', 'Tingir CMO', NULL),
(100433, NULL, NULL, 'Active', NULL, 'CC', 'Marfim CO', 'Tingir CO', NULL),
(100434, NULL, NULL, 'Active', NULL, 'CC', 'Marfim CV', 'Tingir CV', NULL),
(100435, NULL, NULL, 'Active', NULL, 'CC', 'Marfim Fio Tinto', 'Lavar', NULL),
(100436, NULL, NULL, 'Active', NULL, 'CC', 'Marfim PA', 'Tingir PA', NULL),
(100437, NULL, NULL, 'Active', NULL, 'CC', 'Marfim PES', 'Tingir PES', NULL),
(100438, NULL, NULL, 'Active', NULL, 'CC', 'Marfim PV', 'Tingir PV', NULL),
(100439, NULL, NULL, 'Active', NULL, 'CI', 'Marinho CMO', 'Tingir CMO', NULL),
(100440, NULL, NULL, 'Active', NULL, 'CI', 'Marinho CO', 'Tingir CO', NULL),
(100441, NULL, NULL, 'Active', NULL, 'CI', 'Marinho CV', 'Tingir CV', NULL),
(100442, NULL, NULL, 'Active', NULL, 'CI', 'Marinho Fio Tinto', 'Lavar', NULL),
(100443, NULL, NULL, 'Active', NULL, 'CI', 'Marinho PA', 'Tingir PA', NULL),
(100444, NULL, NULL, 'Active', NULL, 'CI', 'Marinho PES', 'Tingir PES', NULL),
(100445, NULL, NULL, 'Active', NULL, 'CI', 'Marinho PV', 'Tingir PV', NULL),
(100446, NULL, NULL, 'Active', NULL, 'CE', 'Menthol CMO', 'Tingir CMO', NULL),
(100447, NULL, NULL, 'Active', NULL, 'CE', 'Menthol CO', 'Tingir CO', NULL),
(100448, NULL, NULL, 'Active', NULL, 'CE', 'Menthol CV', 'Tingir CV', NULL),
(100449, NULL, NULL, 'Active', NULL, 'CE', 'Menthol Fio Tinto', 'Lavar', NULL),
(100450, NULL, NULL, 'Active', NULL, 'CE', 'Menthol PA', 'Tingir PA', NULL),
(100451, NULL, NULL, 'Active', NULL, 'CE', 'Menthol PES', 'Tingir PES', NULL),
(100452, NULL, NULL, 'Active', NULL, 'CE', 'Menthol PV', 'Tingir PV', NULL),
(100453, NULL, NULL, 'Active', NULL, 'CM', 'Metal And CMO', 'Tingir CMO', NULL),
(100454, NULL, NULL, 'Active', NULL, 'CM', 'Metal And CO', 'Tingir CO', NULL),
(100455, NULL, NULL, 'Active', NULL, 'CM', 'Metal And CV', 'Tingir CV', NULL),
(100456, NULL, NULL, 'Active', NULL, 'CM', 'Metal And Fio Tinto', 'Lavar', NULL),
(100457, NULL, NULL, 'Active', NULL, 'CM', 'Metal And PA', 'Tingir PA', NULL),
(100458, NULL, NULL, 'Active', NULL, 'CM', 'Metal And PES', 'Tingir PES', NULL),
(100459, NULL, NULL, 'Active', NULL, 'CM', 'Metal And PV', 'Tingir PV', NULL),
(100460, NULL, NULL, 'Active', NULL, 'CM', 'Metal Blue CMO', 'Tingir CMO', NULL),
(100461, NULL, NULL, 'Active', NULL, 'CM', 'Metal Blue CO', 'Tingir CO', NULL),
(100462, NULL, NULL, 'Active', NULL, 'CM', 'Metal Blue CV', 'Tingir CV', NULL),
(100463, NULL, NULL, 'Active', NULL, 'CM', 'Metal Blue Fio Tinto', 'Lavar', NULL),
(100464, NULL, NULL, 'Active', NULL, 'CM', 'Metal Blue PA', 'Tingir PA', NULL),
(100465, NULL, NULL, 'Active', NULL, 'CM', 'Metal Blue PES', 'Tingir PES', NULL),
(100466, NULL, NULL, 'Active', NULL, 'CM', 'Metal Blue PV', 'Tingir PV', NULL),
(100467, NULL, NULL, 'Active', NULL, 'CI', 'Militar CMO', 'Tingir CMO', NULL),
(100468, NULL, NULL, 'Active', NULL, 'CI', 'Militar CO', 'Tingir CO', NULL),
(100469, NULL, NULL, 'Active', NULL, 'CI', 'Militar CV', 'Tingir CV', NULL),
(100470, NULL, NULL, 'Active', NULL, 'CI', 'Militar Fio Tinto', 'Lavar', NULL),
(100471, NULL, NULL, 'Active', NULL, 'CI', 'Militar PA', 'Tingir PA', NULL),
(100472, NULL, NULL, 'Active', NULL, 'CI', 'Militar PES', 'Tingir PES', NULL),
(100473, NULL, NULL, 'Active', NULL, 'CI', 'Militar PV', 'Tingir PV', NULL),
(100474, NULL, NULL, 'Active', NULL, 'CM', 'Minerio CMO', 'Tingir CMO', NULL),
(100475, NULL, NULL, 'Active', NULL, 'CM', 'Minerio CO', 'Tingir CO', NULL),
(100476, NULL, NULL, 'Active', NULL, 'CM', 'Minerio CV', 'Tingir CV', NULL),
(100477, NULL, NULL, 'Active', NULL, 'CM', 'Minerio Fio Tinto', 'Lavar', NULL),
(100478, NULL, NULL, 'Active', NULL, 'CM', 'Minerio PA', 'Tingir PA', NULL),
(100479, NULL, NULL, 'Active', NULL, 'CM', 'Minerio PES', 'Tingir PES', NULL),
(100480, NULL, NULL, 'Active', NULL, 'CM', 'Minerio PV', 'Tingir PV', NULL),
(100481, NULL, NULL, 'Active', NULL, 'CM', 'Mostarda CMO', 'Tingir CMO', NULL),
(100482, NULL, NULL, 'Active', NULL, 'CM', 'Mostarda CO', 'Tingir CO', NULL),
(100483, NULL, NULL, 'Active', NULL, 'CM', 'Mostarda CV', 'Tingir CV', NULL),
(100484, NULL, NULL, 'Active', NULL, 'CM', 'Mostarda Fio Tinto', 'Lavar', NULL),
(100485, NULL, NULL, 'Active', NULL, 'CM', 'Mostarda PA', 'Tingir PA', NULL),
(100486, NULL, NULL, 'Active', NULL, 'CM', 'Mostarda PES', 'Tingir PES', NULL),
(100487, NULL, NULL, 'Active', NULL, 'CM', 'Mostarda PV', 'Tingir PV', NULL),
(100488, NULL, NULL, 'Active', NULL, 'CI', 'Mousse CMO', 'Tingir CMO', NULL),
(100489, NULL, NULL, 'Active', NULL, 'CI', 'Mousse CO', 'Tingir CO', NULL),
(100490, NULL, NULL, 'Active', NULL, 'CI', 'Mousse CV', 'Tingir CV', NULL),
(100491, NULL, NULL, 'Active', NULL, 'CI', 'Mousse Fio Tinto', 'Lavar', NULL),
(100492, NULL, NULL, 'Active', NULL, 'CI', 'Mousse PA', 'Tingir PA', NULL),
(100493, NULL, NULL, 'Active', NULL, 'CI', 'Mousse PES', 'Tingir PES', NULL),
(100494, NULL, NULL, 'Active', NULL, 'CI', 'Mousse PV', 'Tingir PV', NULL),
(100495, NULL, NULL, 'Active', NULL, 'CI', 'Musgo CMO', 'Tingir CMO', NULL),
(100496, NULL, NULL, 'Active', NULL, 'CI', 'Musgo CO', 'Tingir CO', NULL),
(100497, NULL, NULL, 'Active', NULL, 'CI', 'Musgo CV', 'Tingir CV', NULL),
(100498, NULL, NULL, 'Active', NULL, 'CI', 'Musgo Fio Tinto', 'Lavar', NULL),
(100499, NULL, NULL, 'Active', NULL, 'CI', 'Musgo PA', 'Tingir PA', NULL),
(100500, NULL, NULL, 'Active', NULL, 'CI', 'Musgo PES', 'Tingir PES', NULL),
(100501, NULL, NULL, 'Active', NULL, 'CI', 'Musgo PV', 'Tingir PV', NULL),
(100502, NULL, NULL, 'Active', NULL, 'CM', 'Mushroom CMO', 'Tingir CMO', NULL),
(100503, NULL, NULL, 'Active', NULL, 'CM', 'Mushroom CO', 'Tingir CO', NULL),
(100504, NULL, NULL, 'Active', NULL, 'CM', 'Mushroom CV', 'Tingir CV', NULL),
(100505, NULL, NULL, 'Active', NULL, 'CM', 'Mushroom Fio Tinto', 'Lavar', NULL),
(100506, NULL, NULL, 'Active', NULL, 'CM', 'Mushroom PA', 'Tingir PA', NULL),
(100507, NULL, NULL, 'Active', NULL, 'CM', 'Mushroom PES', 'Tingir PES', NULL),
(100508, NULL, NULL, 'Active', NULL, 'CM', 'Mushroom PV', 'Tingir PV', NULL),
(100509, NULL, NULL, 'Active', NULL, 'CC', 'Natural CMO', 'Tingir CMO', NULL),
(100510, NULL, NULL, 'Active', NULL, 'CC', 'Natural CO', 'Tingir CO', NULL),
(100511, NULL, NULL, 'Active', NULL, 'CC', 'Natural CV', 'Tingir CV', NULL),
(100512, NULL, NULL, 'Active', NULL, 'CC', 'Natural Fio Tinto', 'Lavar', NULL),
(100513, NULL, NULL, 'Active', NULL, 'CC', 'Natural PA', 'Tingir PA', NULL),
(100514, NULL, NULL, 'Active', NULL, 'CC', 'Natural PES', 'Tingir PES', NULL),
(100515, NULL, NULL, 'Active', NULL, 'CC', 'Natural PV', 'Tingir PV', NULL),
(100516, NULL, NULL, 'Active', NULL, 'CM', 'Nectar CMO', 'Tingir CMO', NULL),
(100517, NULL, NULL, 'Active', NULL, 'CM', 'Nectar CO', 'Tingir CO', NULL),
(100518, NULL, NULL, 'Active', NULL, 'CM', 'Nectar CV', 'Tingir CV', NULL),
(100519, NULL, NULL, 'Active', NULL, 'CM', 'Nectar Fio Tinto', 'Lavar', NULL),
(100520, NULL, NULL, 'Active', NULL, 'CM', 'Nectar PA', 'Tingir PA', NULL),
(100521, NULL, NULL, 'Active', NULL, 'CM', 'Nectar PES', 'Tingir PES', NULL),
(100522, NULL, NULL, 'Active', NULL, 'CM', 'Nectar PV', 'Tingir PV', NULL),
(100523, NULL, NULL, 'Active', NULL, 'CE', 'Nivea CMO', 'Tingir CMO', NULL),
(100524, NULL, NULL, 'Active', NULL, 'CE', 'Nivea CO', 'Tingir CO', NULL),
(100525, NULL, NULL, 'Active', NULL, 'CE', 'Nivea CV', 'Tingir CV', NULL),
(100526, NULL, NULL, 'Active', NULL, 'CE', 'Nivea Fio Tinto', 'Lavar', NULL),
(100527, NULL, NULL, 'Active', NULL, 'CE', 'Nivea PA', 'Tingir PA', NULL),
(100528, NULL, NULL, 'Active', NULL, 'CE', 'Nivea PES', 'Tingir PES', NULL),
(100529, NULL, NULL, 'Active', NULL, 'CE', 'Nivea PV', 'Tingir PV', NULL),
(100530, NULL, NULL, 'Active', NULL, 'CI', 'Nozes CMO', 'Tingir CMO', NULL),
(100531, NULL, NULL, 'Active', NULL, 'CI', 'Nozes CO', 'Tingir CO', NULL),
(100532, NULL, NULL, 'Active', NULL, 'CI', 'Nozes CV', 'Tingir CV', NULL),
(100533, NULL, NULL, 'Active', NULL, 'CI', 'Nozes Fio Tinto', 'Lavar', NULL),
(100534, NULL, NULL, 'Active', NULL, 'CI', 'Nozes PA', 'Tingir PA', NULL),
(100535, NULL, NULL, 'Active', NULL, 'CI', 'Nozes PES', 'Tingir PES', NULL),
(100536, NULL, NULL, 'Active', NULL, 'CI', 'Nozes PV', 'Tingir PV', NULL),
(100537, NULL, NULL, 'Active', NULL, 'CI', 'Orange Fluor CMO', 'Tingir CMO', NULL),
(100538, NULL, NULL, 'Active', NULL, 'CI', 'Orange Fluor CO', 'Tingir CO', NULL),
(100539, NULL, NULL, 'Active', NULL, 'CI', 'Orange Fluor CV', 'Tingir CV', NULL),
(100540, NULL, NULL, 'Active', NULL, 'CI', 'Orange Fluor Fio Tinto', 'Lavar', NULL),
(100541, NULL, NULL, 'Active', NULL, 'CI', 'Orange Fluor PA', 'Tingir PA', NULL),
(100542, NULL, NULL, 'Active', NULL, 'CI', 'Orange Fluor PES', 'Tingir PES', NULL),
(100543, NULL, NULL, 'Active', NULL, 'CI', 'Orange Fluor PV', 'Tingir PV', NULL),
(100544, NULL, NULL, 'Active', NULL, 'CM', 'Orange Kin CMO', 'Tingir CMO', NULL),
(100545, NULL, NULL, 'Active', NULL, 'CM', 'Orange Kin CO', 'Tingir CO', NULL),
(100546, NULL, NULL, 'Active', NULL, 'CM', 'Orange Kin CV', 'Tingir CV', NULL),
(100547, NULL, NULL, 'Active', NULL, 'CM', 'Orange Kin Fio Tinto', 'Lavar', NULL),
(100548, NULL, NULL, 'Active', NULL, 'CM', 'Orange Kin PA', 'Tingir PA', NULL),
(100549, NULL, NULL, 'Active', NULL, 'CM', 'Orange Kin PES', 'Tingir PES', NULL),
(100550, NULL, NULL, 'Active', NULL, 'CM', 'Orange Kin PV', 'Tingir PV', NULL),
(100551, NULL, NULL, 'Active', NULL, 'CI', 'Papaya CMO', 'Tingir CMO', NULL),
(100552, NULL, NULL, 'Active', NULL, 'CI', 'Papaya CO', 'Tingir CO', NULL),
(100553, NULL, NULL, 'Active', NULL, 'CI', 'Papaya CV', 'Tingir CV', NULL),
(100554, NULL, NULL, 'Active', NULL, 'CI', 'Papaya Fio Tinto', 'Lavar', NULL),
(100555, NULL, NULL, 'Active', NULL, 'CI', 'Papaya PA', 'Tingir PA', NULL),
(100556, NULL, NULL, 'Active', NULL, 'CI', 'Papaya PES', 'Tingir PES', NULL),
(100557, NULL, NULL, 'Active', NULL, 'CI', 'Papaya PV', 'Tingir PV', NULL),
(100558, NULL, NULL, 'Active', NULL, 'CI', 'Petroleo CMO', 'Tingir CMO', NULL),
(100559, NULL, NULL, 'Active', NULL, 'CI', 'Petroleo CO', 'Tingir CO', NULL),
(100560, NULL, NULL, 'Active', NULL, 'CI', 'Petroleo CV', 'Tingir CV', NULL),
(100561, NULL, NULL, 'Active', NULL, 'CI', 'Petroleo Fio Tinto', 'Lavar', NULL),
(100562, NULL, NULL, 'Active', NULL, 'CI', 'Petroleo PA', 'Tingir PA', NULL),
(100563, NULL, NULL, 'Active', NULL, 'CI', 'Petroleo PES', 'Tingir PES', NULL),
(100564, NULL, NULL, 'Active', NULL, 'CI', 'Petroleo PV', 'Tingir PV', NULL),
(100565, NULL, NULL, 'Active', NULL, 'CI', 'Pink Berry Fluor CMO', 'Tingir CMO', NULL),
(100566, NULL, NULL, 'Active', NULL, 'CI', 'Pink Berry Fluor CO', 'Tingir CO', NULL),
(100567, NULL, NULL, 'Active', NULL, 'CI', 'Pink Berry Fluor CV', 'Tingir CV', NULL),
(100568, NULL, NULL, 'Active', NULL, 'CI', 'Pink Berry Fluor Fio Tinto', 'Lavar', NULL),
(100569, NULL, NULL, 'Active', NULL, 'CI', 'Pink Berry Fluor PA', 'Tingir PA', NULL),
(100570, NULL, NULL, 'Active', NULL, 'CI', 'Pink Berry Fluor PES', 'Tingir PES', NULL),
(100571, NULL, NULL, 'Active', NULL, 'CI', 'Pink Berry Fluor PV', 'Tingir PV', NULL),
(100572, NULL, NULL, 'Active', NULL, 'CI', 'Pink Cot CMO', 'Tingir CMO', NULL),
(100573, NULL, NULL, 'Active', NULL, 'CI', 'Pink Cot CO', 'Tingir CO', NULL),
(100574, NULL, NULL, 'Active', NULL, 'CI', 'Pink Cot CV', 'Tingir CV', NULL),
(100575, NULL, NULL, 'Active', NULL, 'CI', 'Pink Cot Fio Tinto', 'Lavar', NULL),
(100576, NULL, NULL, 'Active', NULL, 'CI', 'Pink Cot PA', 'Tingir PA', NULL),
(100577, NULL, NULL, 'Active', NULL, 'CI', 'Pink Cot PES', 'Tingir PES', NULL),
(100578, NULL, NULL, 'Active', NULL, 'CI', 'Pink Cot PV', 'Tingir PV', NULL),
(100579, NULL, NULL, 'Active', NULL, 'CE', 'Pink Divino CMO', 'Tingir CMO', NULL),
(100580, NULL, NULL, 'Active', NULL, 'CE', 'Pink Divino CO', 'Tingir CO', NULL),
(100581, NULL, NULL, 'Active', NULL, 'CE', 'Pink Divino CV', 'Tingir CV', NULL),
(100582, NULL, NULL, 'Active', NULL, 'CE', 'Pink Divino Fio Tinto', 'Lavar', NULL),
(100583, NULL, NULL, 'Active', NULL, 'CE', 'Pink Divino PA', 'Tingir PA', NULL),
(100584, NULL, NULL, 'Active', NULL, 'CE', 'Pink Divino PES', 'Tingir PES', NULL),
(100585, NULL, NULL, 'Active', NULL, 'CE', 'Pink Divino PV', 'Tingir PV', NULL),
(100586, NULL, NULL, 'Active', NULL, 'CI', 'Pink Fluor CMO', 'Tingir CMO', NULL),
(100587, NULL, NULL, 'Active', NULL, 'CI', 'Pink Fluor CO', 'Tingir CO', NULL),
(100588, NULL, NULL, 'Active', NULL, 'CI', 'Pink Fluor CV', 'Tingir CV', NULL),
(100589, NULL, NULL, 'Active', NULL, 'CI', 'Pink Fluor Fio Tinto', 'Lavar', NULL),
(100590, NULL, NULL, 'Active', NULL, 'CI', 'Pink Fluor PA', 'Tingir PA', NULL),
(100591, NULL, NULL, 'Active', NULL, 'CI', 'Pink Fluor PES', 'Tingir PES', NULL),
(100592, NULL, NULL, 'Active', NULL, 'CI', 'Pink Fluor PV', 'Tingir PV', NULL),
(100593, NULL, NULL, 'Active', NULL, 'CI', 'Pink Neon CMO', 'Tingir CMO', NULL),
(100594, NULL, NULL, 'Active', NULL, 'CI', 'Pink Neon CO', 'Tingir CO', NULL),
(100595, NULL, NULL, 'Active', NULL, 'CI', 'Pink Neon CV', 'Tingir CV', NULL),
(100596, NULL, NULL, 'Active', NULL, 'CI', 'Pink Neon Fio Tinto', 'Lavar', NULL),
(100597, NULL, NULL, 'Active', NULL, 'CI', 'Pink Neon PA', 'Tingir PA', NULL),
(100598, NULL, NULL, 'Active', NULL, 'CI', 'Pink Neon PES', 'Tingir PES', NULL),
(100599, NULL, NULL, 'Active', NULL, 'CI', 'Pink Neon PV', 'Tingir PV', NULL),
(100600, NULL, NULL, 'Active', NULL, 'CE', 'Pomodoro CMO', 'Tingir CMO', NULL),
(100601, NULL, NULL, 'Active', NULL, 'CE', 'Pomodoro CO', 'Tingir CO', NULL),
(100602, NULL, NULL, 'Active', NULL, 'CE', 'Pomodoro CV', 'Tingir CV', NULL),
(100603, NULL, NULL, 'Active', NULL, 'CE', 'Pomodoro Fio Tinto', 'Lavar', NULL),
(100604, NULL, NULL, 'Active', NULL, 'CE', 'Pomodoro PA', 'Tingir PA', NULL),
(100605, NULL, NULL, 'Active', NULL, 'CE', 'Pomodoro PES', 'Tingir PES', NULL),
(100606, NULL, NULL, 'Active', NULL, 'CE', 'Pomodoro PV', 'Tingir PV', NULL),
(100607, NULL, NULL, 'Active', NULL, 'CM', 'Preto CMO', 'Tingir CMO', NULL),
(100608, NULL, NULL, 'Active', NULL, 'CM', 'Preto CO', 'Tingir CO', NULL),
(100609, NULL, NULL, 'Active', NULL, 'CM', 'Preto CV', 'Tingir CV', NULL),
(100610, NULL, NULL, 'Active', NULL, 'CM', 'Preto Fio Tinto', 'Lavar', NULL),
(100611, NULL, NULL, 'Active', NULL, 'CM', 'Preto PA', 'Tingir PA', NULL),
(100612, NULL, NULL, 'Active', NULL, 'CM', 'Preto PES', 'Tingir PES', NULL),
(100613, NULL, NULL, 'Active', NULL, 'CM', 'Preto PV', 'Tingir PV', NULL),
(100614, NULL, NULL, 'Active', NULL, 'CB', 'PT', 'Lavar', NULL),
(100615, NULL, NULL, 'Active', NULL, 'CE', 'Red Fly CMO', 'Tingir CMO', NULL),
(100616, NULL, NULL, 'Active', NULL, 'CE', 'Red Fly CO', 'Tingir CO', NULL),
(100617, NULL, NULL, 'Active', NULL, 'CE', 'Red Fly CV', 'Tingir CV', NULL),
(100618, NULL, NULL, 'Active', NULL, 'CE', 'Red Fly Fio Tinto', 'Lavar', NULL),
(100619, NULL, NULL, 'Active', NULL, 'CE', 'Red Fly PA', 'Tingir PA', NULL),
(100620, NULL, NULL, 'Active', NULL, 'CE', 'Red Fly PES', 'Tingir PES', NULL),
(100621, NULL, NULL, 'Active', NULL, 'CE', 'Red Fly PV', 'Tingir PV', NULL),
(100622, NULL, NULL, 'Active', NULL, 'CC', 'Rice CMO', 'Tingir CMO', NULL),
(100623, NULL, NULL, 'Active', NULL, 'CC', 'Rice CO', 'Tingir CO', NULL),
(100624, NULL, NULL, 'Active', NULL, 'CC', 'Rice CV', 'Tingir CV', NULL),
(100625, NULL, NULL, 'Active', NULL, 'CC', 'Rice Fio Tinto', 'Lavar', NULL),
(100626, NULL, NULL, 'Active', NULL, 'CC', 'Rice PA', 'Tingir PA', NULL),
(100627, NULL, NULL, 'Active', NULL, 'CC', 'Rice PES', 'Tingir PES', NULL),
(100628, NULL, NULL, 'Active', NULL, 'CC', 'Rice PV', 'Tingir PV', NULL),
(100629, NULL, NULL, 'Active', NULL, 'CC', 'Rosa BB CMO', 'Tingir CMO', NULL),
(100630, NULL, NULL, 'Active', NULL, 'CC', 'Rosa BB CO', 'Tingir CO', NULL),
(100631, NULL, NULL, 'Active', NULL, 'CC', 'Rosa BB CV', 'Tingir CV', NULL),
(100632, NULL, NULL, 'Active', NULL, 'CC', 'Rosa BB Fio Tinto', 'Lavar', NULL),
(100633, NULL, NULL, 'Active', NULL, 'CC', 'Rosa BB PA', 'Tingir PA', NULL),
(100634, NULL, NULL, 'Active', NULL, 'CC', 'Rosa BB PES', 'Tingir PES', NULL),
(100635, NULL, NULL, 'Active', NULL, 'CC', 'Rosa BB PV', 'Tingir PV', NULL),
(100636, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Bromelia CMO', 'Tingir CMO', NULL),
(100637, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Bromelia CO', 'Tingir CO', NULL),
(100638, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Bromelia CV', 'Tingir CV', NULL),
(100639, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Bromelia Fio Tinto', 'Lavar', NULL),
(100640, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Bromelia PA', 'Tingir PA', NULL),
(100641, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Bromelia PES', 'Tingir PES', NULL),
(100642, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Bromelia PV', 'Tingir PV', NULL),
(100643, NULL, NULL, 'Active', NULL, 'CC', 'Rosa Cristal CMO', 'Tingir CMO', NULL),
(100644, NULL, NULL, 'Active', NULL, 'CC', 'Rosa Cristal CO', 'Tingir CO', NULL),
(100645, NULL, NULL, 'Active', NULL, 'CC', 'Rosa Cristal CV', 'Tingir CV', NULL),
(100646, NULL, NULL, 'Active', NULL, 'CC', 'Rosa Cristal Fio Tinto', 'Lavar', NULL);
INSERT INTO `Colors` (`id`, `updated_by`, `updated_at`, `status`, `color_code`, `color_type`, `color_name`, `dyeing_type`, `remarks`) VALUES
(100647, NULL, NULL, 'Active', NULL, 'CC', 'Rosa Cristal PA', 'Tingir PA', NULL),
(100648, NULL, NULL, 'Active', NULL, 'CC', 'Rosa Cristal PES', 'Tingir PES', NULL),
(100649, NULL, NULL, 'Active', NULL, 'CC', 'Rosa Cristal PV', 'Tingir PV', NULL),
(100650, NULL, NULL, 'Active', NULL, 'CI', 'Rosa Maravilha CMO', 'Tingir CMO', NULL),
(100651, NULL, NULL, 'Active', NULL, 'CI', 'Rosa Maravilha CO', 'Tingir CO', NULL),
(100652, NULL, NULL, 'Active', NULL, 'CI', 'Rosa Maravilha CV', 'Tingir CV', NULL),
(100653, NULL, NULL, 'Active', NULL, 'CI', 'Rosa Maravilha Fio Tinto', 'Lavar', NULL),
(100654, NULL, NULL, 'Active', NULL, 'CI', 'Rosa Maravilha PA', 'Tingir PA', NULL),
(100655, NULL, NULL, 'Active', NULL, 'CI', 'Rosa Maravilha PES', 'Tingir PES', NULL),
(100656, NULL, NULL, 'Active', NULL, 'CI', 'Rosa Maravilha PV', 'Tingir PV', NULL),
(100657, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Petunia CMO', 'Tingir CMO', NULL),
(100658, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Petunia CO', 'Tingir CO', NULL),
(100659, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Petunia CV', 'Tingir CV', NULL),
(100660, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Petunia Fio Tinto', 'Lavar', NULL),
(100661, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Petunia PA', 'Tingir PA', NULL),
(100662, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Petunia PES', 'Tingir PES', NULL),
(100663, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Petunia PV', 'Tingir PV', NULL),
(100664, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Shake CMO', 'Tingir CMO', NULL),
(100665, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Shake CO', 'Tingir CO', NULL),
(100666, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Shake CV', 'Tingir CV', NULL),
(100667, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Shake Fio Tinto', 'Lavar', NULL),
(100668, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Shake PA', 'Tingir PA', NULL),
(100669, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Shake PES', 'Tingir PES', NULL),
(100670, NULL, NULL, 'Active', NULL, 'CM', 'Rosa Shake PV', 'Tingir PV', NULL),
(100671, NULL, NULL, 'Active', NULL, 'CM', 'Rose Coral CMO', 'Tingir CMO', NULL),
(100672, NULL, NULL, 'Active', NULL, 'CM', 'Rose Coral CO', 'Tingir CO', NULL),
(100673, NULL, NULL, 'Active', NULL, 'CM', 'Rose Coral CV', 'Tingir CV', NULL),
(100674, NULL, NULL, 'Active', NULL, 'CM', 'Rose Coral Fio Tinto', 'Lavar', NULL),
(100675, NULL, NULL, 'Active', NULL, 'CM', 'Rose Coral PA', 'Tingir PA', NULL),
(100676, NULL, NULL, 'Active', NULL, 'CM', 'Rose Coral PES', 'Tingir PES', NULL),
(100677, NULL, NULL, 'Active', NULL, 'CM', 'Rose Coral PV', 'Tingir PV', NULL),
(100678, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Primula CMO', 'Tingir CMO', NULL),
(100679, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Primula CO', 'Tingir CO', NULL),
(100680, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Primula CV', 'Tingir CV', NULL),
(100681, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Primula Fio Tinto', 'Lavar', NULL),
(100682, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Primula PA', 'Tingir PA', NULL),
(100683, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Primula PES', 'Tingir PES', NULL),
(100684, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Primula PV', 'Tingir PV', NULL),
(100685, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Purpura CMO', 'Tingir CMO', NULL),
(100686, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Purpura CO', 'Tingir CO', NULL),
(100687, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Purpura CV', 'Tingir CV', NULL),
(100688, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Purpura Fio Tinto', 'Lavar', NULL),
(100689, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Purpura PA', 'Tingir PA', NULL),
(100690, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Purpura PES', 'Tingir PES', NULL),
(100691, NULL, NULL, 'Active', NULL, 'CE', 'Roxo Purpura PV', 'Tingir PV', NULL),
(100692, NULL, NULL, 'Active', NULL, 'CE', 'Royal Kin CMO', 'Tingir CMO', NULL),
(100693, NULL, NULL, 'Active', NULL, 'CE', 'Royal Kin CO', 'Tingir CO', NULL),
(100694, NULL, NULL, 'Active', NULL, 'CE', 'Royal Kin CV', 'Tingir CV', NULL),
(100695, NULL, NULL, 'Active', NULL, 'CE', 'Royal Kin Fio Tinto', 'Lavar', NULL),
(100696, NULL, NULL, 'Active', NULL, 'CE', 'Royal Kin PA', 'Tingir PA', NULL),
(100697, NULL, NULL, 'Active', NULL, 'CE', 'Royal Kin PES', 'Tingir PES', NULL),
(100698, NULL, NULL, 'Active', NULL, 'CE', 'Royal Kin PV', 'Tingir PV', NULL),
(100699, NULL, NULL, 'Active', NULL, 'CE', 'Rubi CMO', 'Tingir CMO', NULL),
(100700, NULL, NULL, 'Active', NULL, 'CE', 'Rubi CO', 'Tingir CO', NULL),
(100701, NULL, NULL, 'Active', NULL, 'CE', 'Rubi CV', 'Tingir CV', NULL),
(100702, NULL, NULL, 'Active', NULL, 'CE', 'Rubi Fio Tinto', 'Lavar', NULL),
(100703, NULL, NULL, 'Active', NULL, 'CE', 'Rubi PA', 'Tingir PA', NULL),
(100704, NULL, NULL, 'Active', NULL, 'CE', 'Rubi PES', 'Tingir PES', NULL),
(100705, NULL, NULL, 'Active', NULL, 'CE', 'Rubi PV', 'Tingir PV', NULL),
(100706, NULL, NULL, 'Active', NULL, 'CM', 'Sachet CMO', 'Tingir CMO', NULL),
(100707, NULL, NULL, 'Active', NULL, 'CM', 'Sachet CO', 'Tingir CO', NULL),
(100708, NULL, NULL, 'Active', NULL, 'CM', 'Sachet CV', 'Tingir CV', NULL),
(100709, NULL, NULL, 'Active', NULL, 'CM', 'Sachet Fio Tinto', 'Lavar', NULL),
(100710, NULL, NULL, 'Active', NULL, 'CM', 'Sachet PA', 'Tingir PA', NULL),
(100711, NULL, NULL, 'Active', NULL, 'CM', 'Sachet PES', 'Tingir PES', NULL),
(100712, NULL, NULL, 'Active', NULL, 'CM', 'Sachet PV', 'Tingir PV', NULL),
(100713, NULL, NULL, 'Active', NULL, 'CM', 'Salmon Tom CMO', 'Tingir CMO', NULL),
(100714, NULL, NULL, 'Active', NULL, 'CM', 'Salmon Tom CO', 'Tingir CO', NULL),
(100715, NULL, NULL, 'Active', NULL, 'CM', 'Salmon Tom CV', 'Tingir CV', NULL),
(100716, NULL, NULL, 'Active', NULL, 'CM', 'Salmon Tom Fio Tinto', 'Lavar', NULL),
(100717, NULL, NULL, 'Active', NULL, 'CM', 'Salmon Tom PA', 'Tingir PA', NULL),
(100718, NULL, NULL, 'Active', NULL, 'CM', 'Salmon Tom PES', 'Tingir PES', NULL),
(100719, NULL, NULL, 'Active', NULL, 'CM', 'Salmon Tom PV', 'Tingir PV', NULL),
(100720, NULL, NULL, 'Active', NULL, 'CM', 'Samambaia CMO', 'Tingir CMO', NULL),
(100721, NULL, NULL, 'Active', NULL, 'CM', 'Samambaia CO', 'Tingir CO', NULL),
(100722, NULL, NULL, 'Active', NULL, 'CM', 'Samambaia CV', 'Tingir CV', NULL),
(100723, NULL, NULL, 'Active', NULL, 'CM', 'Samambaia Fio Tinto', 'Lavar', NULL),
(100724, NULL, NULL, 'Active', NULL, 'CM', 'Samambaia PA', 'Tingir PA', NULL),
(100725, NULL, NULL, 'Active', NULL, 'CM', 'Samambaia PES', 'Tingir PES', NULL),
(100726, NULL, NULL, 'Active', NULL, 'CM', 'Samambaia PV', 'Tingir PV', NULL),
(100727, NULL, NULL, 'Active', NULL, 'CM', 'Segunda Pele CMO', 'Tingir CMO', NULL),
(100728, NULL, NULL, 'Active', NULL, 'CM', 'Segunda Pele CO', 'Tingir CO', NULL),
(100729, NULL, NULL, 'Active', NULL, 'CM', 'Segunda Pele CV', 'Tingir CV', NULL),
(100730, NULL, NULL, 'Active', NULL, 'CM', 'Segunda Pele Fio Tinto', 'Lavar', NULL),
(100731, NULL, NULL, 'Active', NULL, 'CM', 'Segunda Pele PA', 'Tingir PA', NULL),
(100732, NULL, NULL, 'Active', NULL, 'CM', 'Segunda Pele PES', 'Tingir PES', NULL),
(100733, NULL, NULL, 'Active', NULL, 'CM', 'Segunda Pele PV', 'Tingir PV', NULL),
(100734, NULL, NULL, 'Active', NULL, 'CM', 'Sukita CMO', 'Tingir CMO', NULL),
(100735, NULL, NULL, 'Active', NULL, 'CM', 'Sukita CO', 'Tingir CO', NULL),
(100736, NULL, NULL, 'Active', NULL, 'CM', 'Sukita CV', 'Tingir CV', NULL),
(100737, NULL, NULL, 'Active', NULL, 'CM', 'Sukita Fio Tinto', 'Lavar', NULL),
(100738, NULL, NULL, 'Active', NULL, 'CM', 'Sukita PA', 'Tingir PA', NULL),
(100739, NULL, NULL, 'Active', NULL, 'CM', 'Sukita PES', 'Tingir PES', NULL),
(100740, NULL, NULL, 'Active', NULL, 'CM', 'Sukita PV', 'Tingir PV', NULL),
(100741, NULL, NULL, 'Active', NULL, 'CE', 'Telha CMO', 'Tingir CMO', NULL),
(100742, NULL, NULL, 'Active', NULL, 'CE', 'Telha CO', 'Tingir CO', NULL),
(100743, NULL, NULL, 'Active', NULL, 'CE', 'Telha CV', 'Tingir CV', NULL),
(100744, NULL, NULL, 'Active', NULL, 'CE', 'Telha Fio Tinto', 'Lavar', NULL),
(100745, NULL, NULL, 'Active', NULL, 'CE', 'Telha PA', 'Tingir PA', NULL),
(100746, NULL, NULL, 'Active', NULL, 'CE', 'Telha PES', 'Tingir PES', NULL),
(100747, NULL, NULL, 'Active', NULL, 'CE', 'Telha PV', 'Tingir PV', NULL),
(100748, NULL, NULL, 'Active', NULL, 'CE', 'Terracota CMO', 'Tingir CMO', NULL),
(100749, NULL, NULL, 'Active', NULL, 'CE', 'Terracota CO', 'Tingir CO', NULL),
(100750, NULL, NULL, 'Active', NULL, 'CE', 'Terracota CV', 'Tingir CV', NULL),
(100751, NULL, NULL, 'Active', NULL, 'CE', 'Terracota Fio Tinto', 'Lavar', NULL),
(100752, NULL, NULL, 'Active', NULL, 'CE', 'Terracota PA', 'Tingir PA', NULL),
(100753, NULL, NULL, 'Active', NULL, 'CE', 'Terracota PES', 'Tingir PES', NULL),
(100754, NULL, NULL, 'Active', NULL, 'CE', 'Terracota PV', 'Tingir PV', NULL),
(100755, NULL, NULL, 'Active', NULL, 'CE', 'Toddy CMO', 'Tingir CMO', NULL),
(100756, NULL, NULL, 'Active', NULL, 'CE', 'Toddy CO', 'Tingir CO', NULL),
(100757, NULL, NULL, 'Active', NULL, 'CE', 'Toddy CV', 'Tingir CV', NULL),
(100758, NULL, NULL, 'Active', NULL, 'CE', 'Toddy Fio Tinto', 'Lavar', NULL),
(100759, NULL, NULL, 'Active', NULL, 'CE', 'Toddy PA', 'Tingir PA', NULL),
(100760, NULL, NULL, 'Active', NULL, 'CE', 'Toddy PES', 'Tingir PES', NULL),
(100761, NULL, NULL, 'Active', NULL, 'CE', 'Toddy PV', 'Tingir PV', NULL),
(100762, NULL, NULL, 'Active', NULL, 'CE', 'Tulipa CMO', 'Tingir CMO', NULL),
(100763, NULL, NULL, 'Active', NULL, 'CE', 'Tulipa CO', 'Tingir CO', NULL),
(100764, NULL, NULL, 'Active', NULL, 'CE', 'Tulipa CV', 'Tingir CV', NULL),
(100765, NULL, NULL, 'Active', NULL, 'CE', 'Tulipa Fio Tinto', 'Lavar', NULL),
(100766, NULL, NULL, 'Active', NULL, 'CE', 'Tulipa PA', 'Tingir PA', NULL),
(100767, NULL, NULL, 'Active', NULL, 'CE', 'Tulipa PES', 'Tingir PES', NULL),
(100768, NULL, NULL, 'Active', NULL, 'CE', 'Tulipa PV', 'Tingir PV', NULL),
(100769, NULL, NULL, 'Active', NULL, 'CI', 'Turkis CMO', 'Tingir CMO', NULL),
(100770, NULL, NULL, 'Active', NULL, 'CI', 'Turkis CO', 'Tingir CO', NULL),
(100771, NULL, NULL, 'Active', NULL, 'CI', 'Turkis CV', 'Tingir CV', NULL),
(100772, NULL, NULL, 'Active', NULL, 'CI', 'Turkis Fio Tinto', 'Lavar', NULL),
(100773, NULL, NULL, 'Active', NULL, 'CI', 'Turkis PA', 'Tingir PA', NULL),
(100774, NULL, NULL, 'Active', NULL, 'CI', 'Turkis PES', 'Tingir PES', NULL),
(100775, NULL, NULL, 'Active', NULL, 'CI', 'Turkis PV', 'Tingir PV', NULL),
(100776, NULL, NULL, 'Active', NULL, 'CE', 'Turquaise CMO', 'Tingir CMO', NULL),
(100777, NULL, NULL, 'Active', NULL, 'CE', 'Turquaise CO', 'Tingir CO', NULL),
(100778, NULL, NULL, 'Active', NULL, 'CE', 'Turquaise CV', 'Tingir CV', NULL),
(100779, NULL, NULL, 'Active', NULL, 'CE', 'Turquaise Fio Tinto', 'Lavar', NULL),
(100780, NULL, NULL, 'Active', NULL, 'CE', 'Turquaise PA', 'Tingir PA', NULL),
(100781, NULL, NULL, 'Active', NULL, 'CE', 'Turquaise PES', 'Tingir PES', NULL),
(100782, NULL, NULL, 'Active', NULL, 'CE', 'Turquaise PV', 'Tingir PV', NULL),
(100783, NULL, NULL, 'Active', NULL, 'CE', 'Uva CMO', 'Tingir CMO', NULL),
(100784, NULL, NULL, 'Active', NULL, 'CE', 'Uva CO', 'Tingir CO', NULL),
(100785, NULL, NULL, 'Active', NULL, 'CE', 'Uva CV', 'Tingir CV', NULL),
(100786, NULL, NULL, 'Active', NULL, 'CE', 'Uva Fio Tinto', 'Lavar', NULL),
(100787, NULL, NULL, 'Active', NULL, 'CE', 'Uva PA', 'Tingir PA', NULL),
(100788, NULL, NULL, 'Active', NULL, 'CE', 'Uva PES', 'Tingir PES', NULL),
(100789, NULL, NULL, 'Active', NULL, 'CE', 'Uva PV', 'Tingir PV', NULL),
(100790, NULL, NULL, 'Active', NULL, 'CI', 'Verde Alface CMO', 'Tingir CMO', NULL),
(100791, NULL, NULL, 'Active', NULL, 'CI', 'Verde Alface CO', 'Tingir CO', NULL),
(100792, NULL, NULL, 'Active', NULL, 'CI', 'Verde Alface CV', 'Tingir CV', NULL),
(100793, NULL, NULL, 'Active', NULL, 'CI', 'Verde Alface Fio Tinto', 'Lavar', NULL),
(100794, NULL, NULL, 'Active', NULL, 'CI', 'Verde Alface PA', 'Tingir PA', NULL),
(100795, NULL, NULL, 'Active', NULL, 'CI', 'Verde Alface PES', 'Tingir PES', NULL),
(100796, NULL, NULL, 'Active', NULL, 'CI', 'Verde Alface PV', 'Tingir PV', NULL),
(100797, NULL, NULL, 'Active', NULL, 'CC', 'Verde Aquarela CMO', 'Tingir CMO', NULL),
(100798, NULL, NULL, 'Active', NULL, 'CC', 'Verde Aquarela CO', 'Tingir CO', NULL),
(100799, NULL, NULL, 'Active', NULL, 'CC', 'Verde Aquarela CV', 'Tingir CV', NULL),
(100800, NULL, NULL, 'Active', NULL, 'CC', 'Verde Aquarela Fio Tinto', 'Lavar', NULL),
(100801, NULL, NULL, 'Active', NULL, 'CC', 'Verde Aquarela PA', 'Tingir PA', NULL),
(100802, NULL, NULL, 'Active', NULL, 'CC', 'Verde Aquarela PES', 'Tingir PES', NULL),
(100803, NULL, NULL, 'Active', NULL, 'CC', 'Verde Aquarela PV', 'Tingir PV', NULL),
(100804, NULL, NULL, 'Active', NULL, 'CI', 'Verde Arquipelago CMO', 'Tingir CMO', NULL),
(100805, NULL, NULL, 'Active', NULL, 'CI', 'Verde Arquipelago CO', 'Tingir CO', NULL),
(100806, NULL, NULL, 'Active', NULL, 'CI', 'Verde Arquipelago CV', 'Tingir CV', NULL),
(100807, NULL, NULL, 'Active', NULL, 'CI', 'Verde Arquipelago Fio Tinto', 'Lavar', NULL),
(100808, NULL, NULL, 'Active', NULL, 'CI', 'Verde Arquipelago PA', 'Tingir PA', NULL),
(100809, NULL, NULL, 'Active', NULL, 'CI', 'Verde Arquipelago PES', 'Tingir PES', NULL),
(100810, NULL, NULL, 'Active', NULL, 'CI', 'Verde Arquipelago PV', 'Tingir PV', NULL),
(100811, NULL, NULL, 'Active', NULL, 'CI', 'Verde Azeitona CMO', 'Tingir CMO', NULL),
(100812, NULL, NULL, 'Active', NULL, 'CI', 'Verde Azeitona CO', 'Tingir CO', NULL),
(100813, NULL, NULL, 'Active', NULL, 'CI', 'Verde Azeitona CV', 'Tingir CV', NULL),
(100814, NULL, NULL, 'Active', NULL, 'CI', 'Verde Azeitona Fio Tinto', 'Lavar', NULL),
(100815, NULL, NULL, 'Active', NULL, 'CI', 'Verde Azeitona PA', 'Tingir PA', NULL),
(100816, NULL, NULL, 'Active', NULL, 'CI', 'Verde Azeitona PES', 'Tingir PES', NULL),
(100817, NULL, NULL, 'Active', NULL, 'CI', 'Verde Azeitona PV', 'Tingir PV', NULL),
(100818, NULL, NULL, 'Active', NULL, 'CM', 'Verde BB CMO', 'Tingir CMO', NULL),
(100819, NULL, NULL, 'Active', NULL, 'CM', 'Verde BB CO', 'Tingir CO', NULL),
(100820, NULL, NULL, 'Active', NULL, 'CM', 'Verde BB CV', 'Tingir CV', NULL),
(100821, NULL, NULL, 'Active', NULL, 'CM', 'Verde BB Fio Tinto', 'Lavar', NULL),
(100822, NULL, NULL, 'Active', NULL, 'CM', 'Verde BB PA', 'Tingir PA', NULL),
(100823, NULL, NULL, 'Active', NULL, 'CM', 'Verde BB PES', 'Tingir PES', NULL),
(100824, NULL, NULL, 'Active', NULL, 'CM', 'Verde BB PV', 'Tingir PV', NULL),
(100825, NULL, NULL, 'Active', NULL, 'CE', 'Verde Bonsai CMO', 'Tingir CMO', NULL),
(100826, NULL, NULL, 'Active', NULL, 'CE', 'Verde Bonsai CO', 'Tingir CO', NULL),
(100827, NULL, NULL, 'Active', NULL, 'CE', 'Verde Bonsai CV', 'Tingir CV', NULL),
(100828, NULL, NULL, 'Active', NULL, 'CE', 'Verde Bonsai Fio Tinto', 'Lavar', NULL),
(100829, NULL, NULL, 'Active', NULL, 'CE', 'Verde Bonsai PA', 'Tingir PA', NULL),
(100830, NULL, NULL, 'Active', NULL, 'CE', 'Verde Bonsai PES', 'Tingir PES', NULL),
(100831, NULL, NULL, 'Active', NULL, 'CE', 'Verde Bonsai PV', 'Tingir PV', NULL),
(100832, NULL, NULL, 'Active', NULL, 'CE', 'Verde Boston CMO', 'Tingir CMO', NULL),
(100833, NULL, NULL, 'Active', NULL, 'CE', 'Verde Boston CO', 'Tingir CO', NULL),
(100834, NULL, NULL, 'Active', NULL, 'CE', 'Verde Boston CV', 'Tingir CV', NULL),
(100835, NULL, NULL, 'Active', NULL, 'CE', 'Verde Boston Fio Tinto', 'Lavar', NULL),
(100836, NULL, NULL, 'Active', NULL, 'CE', 'Verde Boston PA', 'Tingir PA', NULL),
(100837, NULL, NULL, 'Active', NULL, 'CE', 'Verde Boston PES', 'Tingir PES', NULL),
(100838, NULL, NULL, 'Active', NULL, 'CE', 'Verde Boston PV', 'Tingir PV', NULL),
(100839, NULL, NULL, 'Active', NULL, 'CE', 'Verde BR CMO', 'Tingir CMO', NULL),
(100840, NULL, NULL, 'Active', NULL, 'CE', 'Verde BR CO', 'Tingir CO', NULL),
(100841, NULL, NULL, 'Active', NULL, 'CE', 'Verde BR CV', 'Tingir CV', NULL),
(100842, NULL, NULL, 'Active', NULL, 'CE', 'Verde BR Fio Tinto', 'Lavar', NULL),
(100843, NULL, NULL, 'Active', NULL, 'CE', 'Verde BR PA', 'Tingir PA', NULL),
(100844, NULL, NULL, 'Active', NULL, 'CE', 'Verde BR PES', 'Tingir PES', NULL),
(100845, NULL, NULL, 'Active', NULL, 'CE', 'Verde BR PV', 'Tingir PV', NULL),
(100846, NULL, NULL, 'Active', NULL, 'CC', 'Verde Caribe CMO', 'Tingir CMO', NULL),
(100847, NULL, NULL, 'Active', NULL, 'CC', 'Verde Caribe CO', 'Tingir CO', NULL),
(100848, NULL, NULL, 'Active', NULL, 'CC', 'Verde Caribe CV', 'Tingir CV', NULL),
(100849, NULL, NULL, 'Active', NULL, 'CC', 'Verde Caribe Fio Tinto', 'Lavar', NULL),
(100850, NULL, NULL, 'Active', NULL, 'CC', 'Verde Caribe PA', 'Tingir PA', NULL),
(100851, NULL, NULL, 'Active', NULL, 'CC', 'Verde Caribe PES', 'Tingir PES', NULL),
(100852, NULL, NULL, 'Active', NULL, 'CC', 'Verde Caribe PV', 'Tingir PV', NULL),
(100853, NULL, NULL, 'Active', NULL, 'CM', 'Verde Ervas CMO', 'Tingir CMO', NULL),
(100854, NULL, NULL, 'Active', NULL, 'CM', 'Verde Ervas CO', 'Tingir CO', NULL),
(100855, NULL, NULL, 'Active', NULL, 'CM', 'Verde Ervas CV', 'Tingir CV', NULL),
(100856, NULL, NULL, 'Active', NULL, 'CM', 'Verde Ervas Fio Tinto', 'Lavar', NULL),
(100857, NULL, NULL, 'Active', NULL, 'CM', 'Verde Ervas PA', 'Tingir PA', NULL),
(100858, NULL, NULL, 'Active', NULL, 'CM', 'Verde Ervas PES', 'Tingir PES', NULL),
(100859, NULL, NULL, 'Active', NULL, 'CM', 'Verde Ervas PV', 'Tingir PV', NULL),
(100860, NULL, NULL, 'Active', NULL, 'CE', 'Verde Evolution CMO', 'Tingir CMO', NULL),
(100861, NULL, NULL, 'Active', NULL, 'CE', 'Verde Evolution CO', 'Tingir CO', NULL),
(100862, NULL, NULL, 'Active', NULL, 'CE', 'Verde Evolution CV', 'Tingir CV', NULL),
(100863, NULL, NULL, 'Active', NULL, 'CE', 'Verde Evolution Fio Tinto', 'Lavar', NULL),
(100864, NULL, NULL, 'Active', NULL, 'CE', 'Verde Evolution PA', 'Tingir PA', NULL),
(100865, NULL, NULL, 'Active', NULL, 'CE', 'Verde Evolution PES', 'Tingir PES', NULL),
(100866, NULL, NULL, 'Active', NULL, 'CE', 'Verde Evolution PV', 'Tingir PV', NULL),
(100867, NULL, NULL, 'Active', NULL, 'CE', 'Verde Floresta CMO', 'Tingir CMO', NULL),
(100868, NULL, NULL, 'Active', NULL, 'CE', 'Verde Floresta CO', 'Tingir CO', NULL),
(100869, NULL, NULL, 'Active', NULL, 'CE', 'Verde Floresta CV', 'Tingir CV', NULL),
(100870, NULL, NULL, 'Active', NULL, 'CE', 'Verde Floresta Fio Tinto', 'Lavar', NULL),
(100871, NULL, NULL, 'Active', NULL, 'CE', 'Verde Floresta PA', 'Tingir PA', NULL),
(100872, NULL, NULL, 'Active', NULL, 'CE', 'Verde Floresta PES', 'Tingir PES', NULL),
(100873, NULL, NULL, 'Active', NULL, 'CE', 'Verde Floresta PV', 'Tingir PV', NULL),
(100874, NULL, NULL, 'Active', NULL, 'CI', 'Verde Fluor CMO', 'Tingir CMO', NULL),
(100875, NULL, NULL, 'Active', NULL, 'CI', 'Verde Fluor CO', 'Tingir CO', NULL),
(100876, NULL, NULL, 'Active', NULL, 'CI', 'Verde Fluor CV', 'Tingir CV', NULL),
(100877, NULL, NULL, 'Active', NULL, 'CI', 'Verde Fluor Fio Tinto', 'Lavar', NULL),
(100878, NULL, NULL, 'Active', NULL, 'CI', 'Verde Fluor PA', 'Tingir PA', NULL),
(100879, NULL, NULL, 'Active', NULL, 'CI', 'Verde Fluor PES', 'Tingir PES', NULL),
(100880, NULL, NULL, 'Active', NULL, 'CI', 'Verde Fluor PV', 'Tingir PV', NULL),
(100881, NULL, NULL, 'Active', NULL, 'CI', 'Verde Folha CMO', 'Tingir CMO', NULL),
(100882, NULL, NULL, 'Active', NULL, 'CI', 'Verde Folha CO', 'Tingir CO', NULL),
(100883, NULL, NULL, 'Active', NULL, 'CI', 'Verde Folha CV', 'Tingir CV', NULL),
(100884, NULL, NULL, 'Active', NULL, 'CI', 'Verde Folha Fio Tinto', 'Lavar', NULL),
(100885, NULL, NULL, 'Active', NULL, 'CI', 'Verde Folha PA', 'Tingir PA', NULL),
(100886, NULL, NULL, 'Active', NULL, 'CI', 'Verde Folha PES', 'Tingir PES', NULL),
(100887, NULL, NULL, 'Active', NULL, 'CI', 'Verde Folha PV', 'Tingir PV', NULL),
(100888, NULL, NULL, 'Active', NULL, 'CM', 'Verde Island CMO', 'Tingir CMO', NULL),
(100889, NULL, NULL, 'Active', NULL, 'CM', 'Verde Island CO', 'Tingir CO', NULL),
(100890, NULL, NULL, 'Active', NULL, 'CM', 'Verde Island CV', 'Tingir CV', NULL),
(100891, NULL, NULL, 'Active', NULL, 'CM', 'Verde Island Fio Tinto', 'Lavar', NULL),
(100892, NULL, NULL, 'Active', NULL, 'CM', 'Verde Island PA', 'Tingir PA', NULL),
(100893, NULL, NULL, 'Active', NULL, 'CM', 'Verde Island PES', 'Tingir PES', NULL),
(100894, NULL, NULL, 'Active', NULL, 'CM', 'Verde Island PV', 'Tingir PV', NULL),
(100895, NULL, NULL, 'Active', NULL, 'CI', 'Verde Jade CMO', 'Tingir CMO', NULL),
(100896, NULL, NULL, 'Active', NULL, 'CI', 'Verde Jade CO', 'Tingir CO', NULL),
(100897, NULL, NULL, 'Active', NULL, 'CI', 'Verde Jade CV', 'Tingir CV', NULL),
(100898, NULL, NULL, 'Active', NULL, 'CI', 'Verde Jade Fio Tinto', 'Lavar', NULL),
(100899, NULL, NULL, 'Active', NULL, 'CI', 'Verde Jade PA', 'Tingir PA', NULL),
(100900, NULL, NULL, 'Active', NULL, 'CI', 'Verde Jade PES', 'Tingir PES', NULL),
(100901, NULL, NULL, 'Active', NULL, 'CI', 'Verde Jade PV', 'Tingir PV', NULL),
(100902, NULL, NULL, 'Active', NULL, 'CE', 'Verde Jamaica CMO', 'Tingir CMO', NULL),
(100903, NULL, NULL, 'Active', NULL, 'CE', 'Verde Jamaica CO', 'Tingir CO', NULL),
(100904, NULL, NULL, 'Active', NULL, 'CE', 'Verde Jamaica CV', 'Tingir CV', NULL),
(100905, NULL, NULL, 'Active', NULL, 'CE', 'Verde Jamaica Fio Tinto', 'Lavar', NULL),
(100906, NULL, NULL, 'Active', NULL, 'CE', 'Verde Jamaica PA', 'Tingir PA', NULL),
(100907, NULL, NULL, 'Active', NULL, 'CE', 'Verde Jamaica PES', 'Tingir PES', NULL),
(100908, NULL, NULL, 'Active', NULL, 'CE', 'Verde Jamaica PV', 'Tingir PV', NULL),
(100909, NULL, NULL, 'Active', NULL, 'CI', 'Verde Lagoa CMO', 'Tingir CMO', NULL),
(100910, NULL, NULL, 'Active', NULL, 'CI', 'Verde Lagoa CO', 'Tingir CO', NULL),
(100911, NULL, NULL, 'Active', NULL, 'CI', 'Verde Lagoa CV', 'Tingir CV', NULL),
(100912, NULL, NULL, 'Active', NULL, 'CI', 'Verde Lagoa Fio Tinto', 'Lavar', NULL),
(100913, NULL, NULL, 'Active', NULL, 'CI', 'Verde Lagoa PA', 'Tingir PA', NULL),
(100914, NULL, NULL, 'Active', NULL, 'CI', 'Verde Lagoa PES', 'Tingir PES', NULL),
(100915, NULL, NULL, 'Active', NULL, 'CI', 'Verde Lagoa PV', 'Tingir PV', NULL),
(100916, NULL, NULL, 'Active', NULL, 'CI', 'Verde Maranhao CMO', 'Tingir CMO', NULL),
(100917, NULL, NULL, 'Active', NULL, 'CI', 'Verde Maranhao CO', 'Tingir CO', NULL),
(100918, NULL, NULL, 'Active', NULL, 'CI', 'Verde Maranhao CV', 'Tingir CV', NULL),
(100919, NULL, NULL, 'Active', NULL, 'CI', 'Verde Maranhao Fio Tinto', 'Lavar', NULL),
(100920, NULL, NULL, 'Active', NULL, 'CI', 'Verde Maranhao PA', 'Tingir PA', NULL),
(100921, NULL, NULL, 'Active', NULL, 'CI', 'Verde Maranhao PES', 'Tingir PES', NULL),
(100922, NULL, NULL, 'Active', NULL, 'CI', 'Verde Maranhao PV', 'Tingir PV', NULL),
(100923, NULL, NULL, 'Active', NULL, 'CM', 'Verde Piscina CMO', 'Tingir CMO', NULL),
(100924, NULL, NULL, 'Active', NULL, 'CM', 'Verde Piscina CO', 'Tingir CO', NULL),
(100925, NULL, NULL, 'Active', NULL, 'CM', 'Verde Piscina CV', 'Tingir CV', NULL),
(100926, NULL, NULL, 'Active', NULL, 'CM', 'Verde Piscina Fio Tinto', 'Lavar', NULL),
(100927, NULL, NULL, 'Active', NULL, 'CM', 'Verde Piscina PA', 'Tingir PA', NULL),
(100928, NULL, NULL, 'Active', NULL, 'CM', 'Verde Piscina PES', 'Tingir PES', NULL),
(100929, NULL, NULL, 'Active', NULL, 'CM', 'Verde Piscina PV', 'Tingir PV', NULL),
(100930, NULL, NULL, 'Active', NULL, 'CE', 'Verde Shake CMO', 'Tingir CMO', NULL),
(100931, NULL, NULL, 'Active', NULL, 'CE', 'Verde Shake CO', 'Tingir CO', NULL),
(100932, NULL, NULL, 'Active', NULL, 'CE', 'Verde Shake CV', 'Tingir CV', NULL),
(100933, NULL, NULL, 'Active', NULL, 'CE', 'Verde Shake Fio Tinto', 'Lavar', NULL),
(100934, NULL, NULL, 'Active', NULL, 'CE', 'Verde Shake PA', 'Tingir PA', NULL),
(100935, NULL, NULL, 'Active', NULL, 'CE', 'Verde Shake PES', 'Tingir PES', NULL),
(100936, NULL, NULL, 'Active', NULL, 'CE', 'Verde Shake PV', 'Tingir PV', NULL),
(100937, NULL, NULL, 'Active', NULL, 'CI', 'Vermelho China CMO', 'Tingir CMO', NULL),
(100938, NULL, NULL, 'Active', NULL, 'CI', 'Vermelho China CO', 'Tingir CO', NULL),
(100939, NULL, NULL, 'Active', NULL, 'CI', 'Vermelho China CV', 'Tingir CV', NULL),
(100940, NULL, NULL, 'Active', NULL, 'CI', 'Vermelho China Fio Tinto', 'Lavar', NULL),
(100941, NULL, NULL, 'Active', NULL, 'CI', 'Vermelho China PA', 'Tingir PA', NULL),
(100942, NULL, NULL, 'Active', NULL, 'CI', 'Vermelho China PES', 'Tingir PES', NULL),
(100943, NULL, NULL, 'Active', NULL, 'CI', 'Vermelho China PV', 'Tingir PV', NULL),
(100944, NULL, NULL, 'Active', NULL, 'CM', 'Vespro CMO', 'Tingir CMO', NULL),
(100945, NULL, NULL, 'Active', NULL, 'CM', 'Vespro CO', 'Tingir CO', NULL),
(100946, NULL, NULL, 'Active', NULL, 'CM', 'Vespro CV', 'Tingir CV', NULL),
(100947, NULL, NULL, 'Active', NULL, 'CM', 'Vespro Fio Tinto', 'Lavar', NULL),
(100948, NULL, NULL, 'Active', NULL, 'CM', 'Vespro PA', 'Tingir PA', NULL),
(100949, NULL, NULL, 'Active', NULL, 'CM', 'Vespro PES', 'Tingir PES', NULL),
(100950, NULL, NULL, 'Active', NULL, 'CM', 'Vespro PV', 'Tingir PV', NULL),
(100951, NULL, NULL, 'Active', NULL, 'CI', 'Violeta CMO', 'Tingir CMO', NULL),
(100952, NULL, NULL, 'Active', NULL, 'CI', 'Violeta CO', 'Tingir CO', NULL),
(100953, NULL, NULL, 'Active', NULL, 'CI', 'Violeta CV', 'Tingir CV', NULL),
(100954, NULL, NULL, 'Active', NULL, 'CI', 'Violeta Fio Tinto', 'Lavar', NULL),
(100955, NULL, NULL, 'Active', NULL, 'CI', 'Violeta PA', 'Tingir PA', NULL),
(100956, NULL, NULL, 'Active', NULL, 'CI', 'Violeta PES', 'Tingir PES', NULL),
(100957, NULL, NULL, 'Active', NULL, 'CI', 'Violeta PV', 'Tingir PV', NULL),
(100958, NULL, NULL, 'Active', NULL, 'CE', 'Wine CMO', 'Tingir CMO', NULL),
(100959, NULL, NULL, 'Active', NULL, 'CE', 'Wine CO', 'Tingir CO', NULL),
(100960, NULL, NULL, 'Active', NULL, 'CE', 'Wine CV', 'Tingir CV', NULL),
(100961, NULL, NULL, 'Active', NULL, 'CE', 'Wine Fio Tinto', 'Lavar', NULL),
(100962, NULL, NULL, 'Active', NULL, 'CE', 'Wine PA', 'Tingir PA', NULL),
(100963, NULL, NULL, 'Active', NULL, 'CE', 'Wine PES', 'Tingir PES', NULL),
(100964, NULL, NULL, 'Active', NULL, 'CE', 'Wine PV', 'Tingir PV', NULL);