DROP   TABLE IF     EXISTS FTP_Loads;
CREATE TABLE IF NOT EXISTS FTP_Loads
( id				BIGINT				NOT NULL AUTO_INCREMENT
, created_by		BIGINT				DEFAULT NULL
, created_at		DATETIME			DEFAULT NULL
, updated_by		BIGINT				DEFAULT NULL
, updated_at		DATETIME			DEFAULT NULL
, status			VARCHAR(32)			DEFAULT 'Active'

, parent_id			BIGINT				DEFAULT NULL

, input_from		INT(11)				DEFAULT 0
, input_upto		INT(11)				DEFAULT 0
, thread_id_1		BIGINT				DEFAULT NULL
, thread_id_2		BIGINT				DEFAULT NULL
, thread_id_3		BIGINT				DEFAULT NULL
, thread_id_4		BIGINT				DEFAULT NULL
, remarks			VARCHAR(255)		DEFAULT NULL

, PRIMARY KEY(id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1
;

ALTER TABLE FTP_Loads		ADD COLUMN thread_id_4    			BIGINT   		DEFAULT NULL  AFTER thread_id_3;

ALTER TABLE FTP_Loads		CHANGE	ftp_id		parent_id		BIGINT			DEFAULT NULL;
