DROP   TABLE IF     EXISTS ProductsImp;
CREATE TABLE IF NOT EXISTS ProductsImp
( product_name		VARCHAR(255)		DEFAULT NULL

, UNIQUE(product_name)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1
;
